### ISSUE TITLE
How to configure bar chart?

### ISSUE THREAD

**Issue by jasonlaw** [entronad/graphic#103]
May I know how to configure bar chart like below?

![image](https://user-images.githubusercontent.com/107820/168744165-d3a17e96-a5c2-4d16-8d16-12969d854de5.png)

Basically I have data that need to group by year, for value of multiple category but I don't want the bar chart stacked as in the example.

**Comment by entronad** [comment]
See in the example app:
https://github.com/entronad/graphic/blob/45963fee4673faf6ad95b7fd9355264c2cc8b7d1/example/lib/pages/polygon_custom.dart#L520

**Comment by jasonlaw** [comment]
Thanks!
