### ISSUE TITLE
When there is a lot of data, the bars are squeezed together，how to config

### ISSUE THREAD

**Issue by xilanzouwei** [entronad/graphic#104]
![image](https://user-images.githubusercontent.com/45849852/169230893-6bd76699-f9f9-4f9a-97b6-bb0265cd89c6.png)

**Comment by entronad** [comment]
Can you provide the spec code and example data?

**Comment by xilanzouwei** [comment]
I just changed the data for the example  ’Stacked Bar Chart‘， 
![image](https://user-images.githubusercontent.com/45849852/169499148-df154d42-bf27-4d2c-96f5-209ff9158a4a.png)

**Comment by entronad** [comment]
The width of the bar is controlled by `size` attribute of the element, you can set it to avoid squeezing

**Comment by xilanzouwei** [comment]
I want to implement a mixed graph, stacked bar with line, is there any example?

**Comment by entronad** [comment]
the `elements` recives a list, you can define a stacked interval element, a line element, and a point element in that list (imagin that tree individal graphs in the same coord) will implement the chart above.

**Comment by xilanzouwei** [comment]
in the example ’Stacked Bar Chart‘,i want show type 'Search' with line chart, other types with stack bar .
`const adjustData = [
  {"type": "Email", "index": 0, "value": 120},
  {"type": "Email", "index": 1, "value": 132},
  {"type": "Email", "index": 2, "value": 101},
  {"type": "Email", "index": 3, "value": 134},
  {"type": "Email", "index": 4, "value": 90},
  {"type": "Email", "index": 5, "value": 230},
  {"type": "Email", "index": 6, "value": 210},
  {"type": "Affiliate", "index": 0, "value": 220},
  {"type": "Affiliate", "index": 1, "value": 182},
  {"type": "Affiliate", "index": 2, "value": 191},
  {"type": "Affiliate", "index": 3, "value": 234},
  {"type": "Affiliate", "index": 4, "value": 290},
  {"type": "Affiliate", "index": 5, "value": 330},
  {"type": "Affiliate", "index": 6, "value": 310},
  {"type": "Video", "index": 0, "value": 150},
  {"type": "Video", "index": 1, "value": 232},
  {"type": "Video", "index": 2, "value": 201},
  {"type": "Video", "index": 3, "value": 154},
  {"type": "Video", "index": 4, "value": 190},
  {"type": "Video", "index": 5, "value": 330},
  {"type": "Video", "index": 6, "value": 410},
  {"type": "Direct", "index": 0, "value": 320},
  {"type": "Direct", "index": 1, "value": 332},
  {"type": "Direct", "index": 2, "value": 301},
  {"type": "Direct", "index": 3, "value": 334},
  {"type": "Direct", "index": 4, "value": 390},
  {"type": "Direct", "index": 5, "value": 330},
  {"type": "Direct", "index": 6, "value": 320},
  {"type": "Search", "index": 0, "value1": 320},
  {"type": "Search", "index": 1, "value1": 432},
  {"type": "Search", "index": 2, "value1": 401},
  {"type": "Search", "index": 3, "value1": 434},
  {"type": "Search", "index": 4, "value1": 390},
  {"type": "Search", "index": 5, "value1": 430},
  {"type": "Search", "index": 6, "value1": 420},
];`
`Chart(
                  data: adjustData,
                  variables: {
                    'index': Variable(
                      accessor: (Map map) => map['index'].toString(),
                    ),
                    'type': Variable(
                      accessor: (Map map) => map['type'] as String,
                    ),
                    'value': Variable(
                      accessor: (Map map) => map['value'] as num,
                      scale: LinearScale(min: 0, max: 1800),
                    ),
                    'value1': Variable(
                      accessor: (Map map) => map['value1'] as num,
                      scale: LinearScale(),
                    ),
                  },
                  elements: [
                    IntervalElement(
                      position:
                          Varset('index') * Varset('value') / Varset('type'),
                      shape: ShapeAttr(value: RectShape(labelPosition: 0.5)),
                      color: ColorAttr(
                          variable: 'type', values: Defaults.colors10),
                      label: LabelAttr(
                          encoder: (tuple) => Label(
                                tuple['value'].toString(),
                                LabelStyle(style: const TextStyle(fontSize: 6)),
                              )),
                      modifiers: [StackModifier()],
                    ),
                    LineElement(
                      position:
                          Varset('index') * Varset('value1'),
                    )
                  ],)`
i can't  get the line with error  'Expected a value of type 'List<List<Aes>>', but got one of type 'Null''

**Comment by entronad** [comment]
The problem is since you concat the value and value1 tuples, some of their field values are null that you can't always use `as num`, fix the accessors like:
```
             'value': Variable(
                accessor: (Map map) => map['value'] is num ? map['value'] as num : double.nan,
                scale: LinearScale(min: 0, max: 1800),
              ),
              'value1': Variable(
                accessor: (Map map) => map['value1'] is num ? map['value1'] as num : double.nan,
                scale: LinearScale(),
              ),
```
