### ISSUE TITLE
[Feature Request] Add ability to specify axes titles

### ISSUE THREAD

**Issue by bernardobelchior** [entronad/graphic#110]
Hey, there!

Graphic is amazing and I believe we could make it even better by allowing consumers of this library to specify axes titles.
For example, Google Sheets allows this:
![6 and a](https://user-images.githubusercontent.com/12778398/170062403-84849f7f-9ac7-4e29-a4c0-1358e51a75dc.png)

It can be very useful to specify such titles so that it's clear what a chart represents. For example, when showing velocity over time, it can be helpful to add a title such as "Velocity (m/s)" to ensure the reader knows what an axis represents as well as its unit.

As far as I know, there's no way to do this with graphic, right? 
Do you have any idea how that might be implemented? I can try to make a PR, but would appreciate some guidance first

**Comment by entronad** [comment]
You can use a TagAnnotation with absolute position to create an axis title, it has a highly customizable label property:
https://pub.dev/documentation/graphic/latest/graphic/TagAnnotation-class.html

I believe it can fully cover all an axis title property can do, and it's more flexible.

**Comment by bernardobelchior** [comment]
That did work, thanks, @entronad 😄
