### ISSUE TITLE
Any way to add border line to the borders of stacked area?

### ISSUE THREAD

**Issue by elmar001** [entronad/graphic#111]
Is it possible? I am using stacked area chart - River chart from you example app. I mean solid border line to the stacked areas so the overlapping parts can be still visible.

**Comment by entronad** [comment]
Custom your own area shape class, copy the built-in method and add borders (The path has been calculated) here:
https://github.com/entronad/graphic/blob/f2fdb846ae4fa8854f3a437a234459eb08856c17/lib/src/shape/area.dart#L145

**Comment by elmar001** [comment]
Thanks, really appreciate it
