### ISSUE TITLE
怎么实现雷达图效果？

### ISSUE THREAD

**Issue by codertiany** [entronad/graphic#114]

**Comment by entronad** [comment]
https://github.com/entronad/graphic/blob/ad1942884af2f2b361d92758a8ff27a31c74efff/example/lib/pages/line_area_point.dart#L373

**Comment by codertiany** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by codertiany** [comment]
> https://github.com/entronad/graphic/blob/ad1942884af2f2b361d92758a8ff27a31c74efff/example/lib/pages/line_area_point.dart#L373

能否实现类似那种网状的雷达图，类似您的echarts
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/11660271/171981571-9a630c1e-3166-4ae1-89bf-429e46404b37.png">

**Comment by entronad** [comment]
坐标轴网格不能是这种多边形的，只能是圆弧形的

**Comment by cbbfcd** [comment]
请问目前支持多边形了吗？

**Comment by codertiany** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
