### ISSUE TITLE
Add a permanent slider to the line graph

### ISSUE THREAD

**Issue by BentEngbers** [entronad/graphic#115]
We would like to add a slider to graph for visual input.
![](https://google.github.io/charts/flutter/example/behaviors/slider_full.png)

This is from the google charts_flutter library.
(https://google.github.io/charts/flutter/example/behaviors/slider)

**Comment by entronad** [comment]
There is no plan for this yet.

**Comment by entronad** [comment]
The slider can be made of a `TooltipGuide` and a vertical `CrosshairGuide`, with the tooltip's renderer, you can custom the style of the slider button.

Tooltip and crosshair is triggered by selections, if you set the selection's `clear` to an empty set, it will never be cleared. and you can set the element's `selected` to let it show at beginning.

**Comment by LucaCras** [comment]
How should one use the selected property? As using the code below, I do not see the crosshair at the start.

I have used it as follows:
`
LineElement(
    selected: {
    "touchMove": {0}
    },
    shape: ShapeAttr(value: BasicLineShape(dash: [5, 2])))
`

`
selections: {
  'touchMove': PointSelection(
    on: {
      GestureType.scaleUpdate,
      GestureType.tapDown,
      GestureType.longPressMoveUpdate
    },
    dim: Dim.x,
  )
},
`

`
crosshair: CrosshairGuide(followPointer: [false, true])
`

**Comment by LucaCras** [comment]
Thanks again!

**Comment by entronad** [comment]
You sed correctly. But there is a bug before (this feature is not used often enough to trigger this bug).

I have fixed it in v0.10.5, please upgrade and try.
