### ISSUE TITLE
Coordinate Graph

### ISSUE THREAD

**Issue by gtuceturan** [entronad/graphic#117]
Hello,

I was created with echart flutter extention blow graph
![test](https://user-images.githubusercontent.com/59597081/172159944-decdd7fa-9650-405b-9276-704218c49201.png)

dataObjj.add([0.325,-0.6757])
dataObjj.add([-0.462,-0.8069])
dataObjj.add([-0.746,-0.0765])
dataObjj.add([-0.4663,0.8046])
dataObjj.add([0.42303,0.6193])
dataObjj.add([0.42303,-0.6193])

    List _circleData = [];
    List _circleData2 = [];
    _phaseAngles = [];
    _voltagePhase = [];
    for (int i = 0; i <= 360; i++) {
      double rad = (i / 180) * pi;
      _circleData.add([cos(rad) * 0.75, sin(rad) * 0.75]);
      _circleData2.add([cos(rad) * 0.25, sin(rad) * 0.25]);
    }
I use this code

{
   animation: true,
  grid: {    top: 50, left: 50, right: 50, bottom: 50},
  polar: {},
  angleAxis: { min: 0, max: 360, interval: 30, startAngle: 0, clockwise:false,
                     axisTick:{    show:false, },
  },
  radiusAxis: { min: 0,  max: 2, show:false
  },  
  backgroundColor:"#ced4e31a",

  xAxis: {
    minorTick: { show: false },
    minorSplitLine: {  show: false },
    axisLine:{ show:false },
    min: -1,   max: 1,
    axisLabel:{ show:false }    ,
    splitLine: { show: false },
    axisTick:{ show:false, },
  },
  yAxis: {
      minorTick: { show: false},
    minorSplitLine: {show: false},
    axisLine:{ show:false},
    min: -1, max: 1,
    axisLabel:{ show:false }    ,
    splitLine: { show: false},
    axisTick:{ show:false, },
  },
  series: [
    { type: 'line', showSymbol: false, clip: true, data:[[0,0],${dataObjj[0]}],
      lineStyle:{ width:2.3},
       endLabel: { show: true, formatter: "Va" },
       itemStyle:{color:"#040513FF" },
    },
   { type: 'line', showSymbol: false, clip: true,  data:[[0,0],${dataObjj[1]}],
      lineStyle:{width:1.5 },
       endLabel: { show: true, formatter: "Ia"},
       itemStyle:{color:"#040513FF", },
    },
       {
      type: 'line',showSymbol: false,clip: true,data:[[0,0],${dataObjj[2]}],
      lineStyle:{width:2.3},
       endLabel: { show: true, formatter: "Vb"},
      itemStyle:{ color:"#E81A1AFF", },
    },
        {type: 'line', showSymbol: false, clip: true,data:[[0,0],${dataObjj[3]}],
      lineStyle:{width:1.5 },
       endLabel: { show: true,formatter: "Ib" },
       itemStyle:{ color:"#E81A1AFF",},
    },   {
      type: 'line',showSymbol: false, clip: true, data:[[0,0],${dataObjj[4]}],
      lineStyle:{ width:2.3},
       endLabel: {show: true,formatter: "Vc" },
       itemStyle:{color:"#448AFFFF",},
    },
       {
      type: 'line', showSymbol: false,clip: true,data:[[0,0],${dataObjj[5]}],
      lineStyle:{width:1.5 },
       endLabel: {show: true,formatter: "Ic"},
       itemStyle:{color:"#448AFFFF",},
    },
       { type: 'line', showSymbol: false,clip: true, data:${_circleData},
      itemStyle:{color:"#000000FF",opacity:0.2 },
     lineStyle:{width:0.8, type:"dashed"}
    },
    {
      type: 'line',showSymbol: false, clip: true, data:${_circleData2},
      itemStyle:{color:"#000000FF", opacity:0.2},
  lineStyle:{ width:0.8, type:"dashed"
     }
    }
  ]
}

But I couldn't with this library cCan you help me?

**Comment by entronad** [comment]
Please refer to the line chart examples here: https://github.com/entronad/graphic/blob/main/example/lib/pages/line_area_point.dart

To achieve multi lines, you should add the start points and mark the groups, like:
```
[
  {'x': 0, 'y': 0, 'type': 'Ia'},
  {'x': 323, 'y': 32, 'type': 'Ia'},
  {'x': 0, 'y': 0, 'type': 'Vb'},
  {'x': -44, 'y': 33, 'type': 'Vb'},
]
```
Then group them with a nest operator: https://pub.dev/documentation/graphic/latest/graphic/Varset-class.html

You will get the short lines you need.

The circle can be made by a MarkAnnotation: https://pub.dev/documentation/graphic/latest/graphic/MarkAnnotation-class.html

See details in the example app and documents

**Comment by gtuceturan** [comment]
> Please refer to the line chart examples here: https://github.com/entronad/graphic/blob/main/example/lib/pages/line_area_point.dart
> 
> To achieve multi lines, you should add the start points and mark the groups, like:
> 
> ```
> [
>   {'x': 0, 'y': 0, 'type': 'Ia'},
>   {'x': 323, 'y': 32, 'type': 'Ia'},
>   {'x': 0, 'y': 0, 'type': 'Vb'},
>   {'x': -44, 'y': 33, 'type': 'Vb'},
> ]
> ```
> 
> Then group them with a nest operator: https://pub.dev/documentation/graphic/latest/graphic/Varset-class.html
> 
> You will get the short lines you need.
> 
> The circle can be made by a MarkAnnotation: https://pub.dev/documentation/graphic/latest/graphic/MarkAnnotation-class.html
> 
> See details in the example app and documents



I tried  with this values

 Va=(0.83,0.0)
 Ia = (0.3344653057751964,-0.6712920074250135)
 Vb=(-0.41176143695531514,-0.7206611679815237)
 Ib=(-0.7457946531081883,0.07931163467762573)
 Vc=(-0.41705653301621776,0.7176098161734499
 Ic=(0.4192250983155804,0.6218925284502878)

 Chart(
                  data: [
                    {'x': 0, 'y': 0, 'type': 'Va'},
                    {'x': _phaseDiagram[0][0], 'y': _phaseDiagram[0][1], 'type': 'Va'},
                    {'x': 0, 'y': 0, 'type': 'Ia'},
                    {'x': _phaseDiagram[1][0], 'y': _phaseDiagram[1][1], 'type': 'Ia'},
                    {'x': 0, 'y': 0, 'type': 'Vb'},
                    {'x': _phaseDiagram[2][0], 'y': _phaseDiagram[2][1], 'type': 'Vb'},
                    {'x': 0, 'y': 0, 'type': 'Ib'},
                    {'x': _phaseDiagram[3][0], 'y': _phaseDiagram[3][1], 'type': 'Ib'},
                    {'x': 0, 'y': 0, 'type': 'Vc'},
                    {'x': _phaseDiagram[4][0], 'y': _phaseDiagram[4][1], 'type': 'Vc'},
                    {'x': 0, 'y': 0, 'type': 'Ic'},
                    {'x': _phaseDiagram[5][0], 'y': _phaseDiagram[5][1], 'type': 'Ic'},
                  ],
                  variables: {
                    'index': Variable(
                      accessor: (Map map) => map['x'] as num,
                    ),
                    'type': Variable(
                      accessor: (Map map) => map['y'] as num,
                    ),
                    'value': Variable(
                      accessor: (Map map) => map['type'] as String,
                    ),
                  },
                  elements: [
                    LineElement(
                      position:
                      Varset('index') * Varset('value') / Varset('type'),
                      shape: ShapeAttr(value: BasicLineShape(loop: true)),
                      color: ColorAttr(
                          variable: 'type', values: Defaults.colors10),
                    )
                  ],
                  coord: PolarCoord(),
                  axes: [
                    Defaults.circularAxis,
                    Defaults.radialAxis,
                  ],
                  selections: {
                    'touchMove': PointSelection(
                      on: {
                        GestureType.scaleUpdate,
                        GestureType.tapDown,
                        GestureType.longPressMoveUpdate
                      },
                      dim: Dim.x,
                      variable: 'index',
                    )
                  },
                  tooltip: TooltipGuide(
                    anchor: (_) => Offset.zero,
                    align: Alignment.bottomRight,
                    multiTuples: true,
                    variables: ['type', 'value'],
                  ),
                  crosshair: CrosshairGuide(followPointer: [false, true]),
                )

but graph view like this

![Screenshot_20220825-134812 1 jpg](https://user-images.githubusercontent.com/59597081/186647200-efe4e2e0-fd4c-486a-bd76-c9aee02402d1.png)
