### ISSUE TITLE
How to remove horizontal line of CrosshairGuide?

### ISSUE THREAD

**Issue by elmar001** [entronad/graphic#121]
There are cross vertical and horizontal selection point lines when clicked on chart. Is it possible to remove horizontal one? I played with  CrosshairGuide(followPointer: [true, true]), values a bit. It partially helped on one side of the chart but still shows cross horizontal and vertical lines on the some parts of the chart.

**Comment by entronad** [comment]
`CrosshairGuide.style` is a list, it's items represent for each dimension. Set the second item to null, it represents the horizontal one (if not transposed).

**Comment by elmar001** [comment]
Thanks heaps, really helpful
