### ISSUE TITLE
如果某一个数据为空或者null，该什么处理

### ISSUE THREAD

**Issue by yuxingmin** [entronad/graphic#123]

**Comment by yuxingmin** [comment]
a value is null,haw to do?


const basicData = [
  {'genre': 'Sports', 'sold': 275},
  {'genre': 'Strategy', 'sold': null},
  {'genre': 'Action', 'sold': 120},
  {'genre': 'Shooter', 'sold': 350},
  {'genre': 'Other', 'sold': 150},
];

**Comment by entronad** [comment]
在 accessor 中将空值转换为 double.nan
