### ISSUE TITLE
showing growable error

### ISSUE THREAD

**Issue by samuelxencov** [entronad/graphic#125]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
E/flutter (10946): #0      List.first (dart:core-patch/growable_array.dart:360:5)
E/flutter (10946): #1      new TimeScaleConv (package:graphic/src/scale/time.dart:49:27)
E/flutter (10946): #2      ScaleConvOp.evaluate (package:graphic/src/scale/scale.dart:155:21)
E/flutter (10946): #3      Operator.run (package:graphic/src/dataflow/operator.dart:87:29)
E/flutter (10946): #4      Dataflow.evaluate (package:graphic/src/dataflow/dataflow.dart:95:27)
E/flutter (10946): #5      View.evaluate (package:graphic/src/chart/view.dart:69:17)
E/flutter (10946): #6      Dataflow.run (package:graphic/src/dataflow/dataflow.dart:123:16)
E/flutter (10946): #7      new View (package:graphic/src/chart/view.dart:25:5)
E/flutter (10946): #8      _ChartLayoutDelegate.getPositionForChild (package:graphic/src/chart/chart.dart:680:20)
E/flutter (10946): #9      RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1363:41)
E/flutter (10946): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #11     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
E/flutter (10946): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #15     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277:14)
E/flutter (10946): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #17     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
E/flutter (10946): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #19     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
E/flutter (10946): #20     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
E/flutter (10946): #21     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
E/flutter (10946): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #26     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
E/flutter (10946): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #29     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
E/flutter (10946): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #33     RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1361:14)
E/flutter (10946): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #36     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
E/flutter (10946): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #51     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3430:13)
E/flutter (10946): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
E/flutter (10946): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
E/flutter (10946): #55     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:751:15)
E/flutter (10946): #56     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731:7)
E/flutter (10946): #57     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
E/flutter (10946): #58     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
E/flutter (10946): #59     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
E/flutter (10946): #60     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
E/flutter (10946): #61     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
E/flutter (10946): #62     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (10946): #63     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (10946): #64     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)

Here my code , can any on tell how to solve that. I want to create the Real Time series graph. I am using Firebase to get real time value.

seriesData.add(TimeSeriesSales(
    DateTime(
      newTime.year,
      newTime.month,
      newTime.day,
      newTime.hour,
      newTime.minute,
      newTime.second,
    ),
    realValue));

final List<TimeSeriesSales> seriesData = [];

Container(
  padding: const EdgeInsets.all(10),
  color: Colors.grey.shade300,
  width: 350,
  height: 300,
  child: Chart(
    data: seriesData,
    rebuild: true,
    changeData: true,
    variables: {
      'time': Variable(
        accessor: (TimeSeriesSales kk) => kk.time,
        scale: TimeScale(
          formatter: (time) => _monthDayFormat.format(time),
        ),
      ),
      'sales': Variable(
        accessor: (TimeSeriesSales ll) => ll.sales,
      ),
    },
    elements: [
      LineElement(
        shape: ShapeAttr(value: BasicLineShape(loop: true)),
        selected: {
          'touchMove': {1}
        },
      )
    ],
    axes: [
      Defaults.horizontalAxis,
      Defaults.verticalAxis,
    ],
    selections: {
      'touchMove': PointSelection(on: {
        GestureType.scaleUpdate,
        GestureType.tapDown,
        GestureType.longPressMoveUpdate
      }, dim: 1)
    },
    tooltip: TooltipGuide(
      followPointer: [false, true],
      align: Alignment.topLeft,
      backgroundColor: AppColors.activeBtnColor,
      offset: const Offset(-20, -20),
    ),
    crosshair: CrosshairGuide(followPointer: [false, false]),
  ),
),

class TimeSeriesSales {
  final DateTime time;
  num sales;

  TimeSeriesSales(this.time, this.sales);
}

**Comment by entronad** [comment]
The timeScale, if `min` and `max` are not set, will get the range from data values. In this case you have to ensure your data list is not empty. Or you will have to set the `min` and `max`.

**Comment by samuelxencov** [comment]
Can you give any example to do that or Can you modify our code which can really help me.

**Comment by entronad** [comment]
scale: TimeScale(
formatter: (time) => _monthDayFormat.format(time),
min: oneDayBeforeNow,
max: now,
),
