### ISSUE TITLE
Selection 当图表未加载数据时 报错

### ISSUE THREAD

**Issue by lwp001** [entronad/graphic#128]
在图表设置 hover 显示 tooltip时 当图表数据为空时 报错：

[ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: -1, stack trace: #0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      PointSelector.select (package:graphic/src/interaction/selection/point.dart:135:27)
#2      SelectOp.evaluate (package:graphic/src/interaction/selection/selection.dart:336:40)
#3      Operator.run (package:graphic/src/dataflow/operator.dart:95:29)
#4      Dataflow.evaluate (package:graphic/src/dataflow/dataflow.dart:94:27)
#5      View.evaluate (package:graphic/src/chart/view.dart:78:17)
#6      Dataflow.run (package:graphic/src/dataflow/dataflow.dart:122:16)
#7      Dataflow.bindChannel.<anonymous closure> (package:graphic/src/dataflow/dataflow.dart:154:7)
#8      _rootRunUnary (dart:async/zone.dart:1442:13)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1621:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#14     _rootRun (dart:async/zone.dart:1418:47)
#15     _CustomZone.run (dart:async/zone.dart:1328:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#18     _rootRun (dart:async/zone.dart:1426:13)
#19     _CustomZone.run (dart:async/zone.dart:1328:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
 
是否可以在数据为空时 不触发 selections 动作

**Comment by entronad** [comment]
不要让图表的数据为空，会发生很多未知问题
