### ISSUE TITLE
Show initial tooltip on build

### ISSUE THREAD

**Issue by sprimm98** [entronad/graphic#129]
I'm using a pie chart as provided in [https://github.com/entronad/graphic/blob/main/example/lib/pages/polygon_custom.dart](polygon_custom.dart) with a central label that shows up on tap selection. I wonder if there is an option to have an initial selection, like the first entry of the provided data, whose label is shown immediately after build without any user interaction. Thanks in advance.

**Comment by entronad** [comment]
Set the element's `selected`

**Comment by sprimm98** [comment]
Thanks! For anyone interested: When using point selection on tap, you can set `selected: {"tap": {1},},` on the element to achieve this behavior.
