### ISSUE TITLE
Tap instead of double tap to close tooltips

### ISSUE THREAD

**Issue by absar** [entronad/graphic#134]
We are considering using this library, however the default behavior of `double tap` instead of `tap` to close tooltips and crosshairs is preventing us from adapting it. Double tap is not very intuitive since its standard behavior on cell phones to tap for selection and tap again for deselection for better UX, whereas double tap is usually used for zooming in. Is it possible to change this default behavior and use single tap to close tooltips and crosshairs?
Other than that, wanted to appreciate the API, it is very well designed and looks highly customizable, and the accompanied medium article is really helpful

**Comment by entronad** [comment]
Tooltip is controlled by selections. The gestures set for trigger or clear a selection is in `Selection.on` and `Selection.clear`, you can set what ever gestures you want. but don't set one gesture in both `on` and `clear`, because that is ambiguous.

**Comment by absar** [comment]
Thank you for the reply, will experiment with it
