### ISSUE TITLE
静态数据没问题，一加载赋值后就类型报错

### ISSUE THREAD

**Issue by ILittleNiZi** [entronad/graphic#136]
会执行到final accessor = variableSpecs[field]!.accessor; 报 type '(Map<dynamic, dynamic>) => String' is not a subtype of type '(dynamic) => dynamic'。
就好奇怪，data的赋值 用List 定义的数据就不行，他不就是个List<dynamic>吗，赋值了个List<map>类型的值就又报错执行不了

**Comment by ijoywan** [comment]
最后你是怎么解决的？

**Comment by miaoyuxuan** [comment]
接收外部传入的List，我在修改后，定义成这样解决了：
```

**Comment by miaoyuxuan** [comment]
@ijoywan @ILittleNiZi 试试这样：
final List<Map<dynamic, dynamic>> data;
