### ISSUE TITLE
Line Element Colors

### ISSUE THREAD

**Issue by gtuceturan** [entronad/graphic#144]
Hello ,

I plot with Echart this chart

![MicrosoftTeams-image2](https://user-images.githubusercontent.com/59597081/187860705-fd2ec2c7-7ad2-4655-b2d3-a9fb5a550f09.png)

and you helped me this issues 
https://github.com/entronad/graphic/issues/117 I plot with this library

![Screenshot_20220831-162833](https://user-images.githubusercontent.com/59597081/187861247-60830258-3d9d-4ac9-ab59-dd716c8bf2ce.jpg)

but couldn't chance LineElement colors and circle dots can you help?  My code is below;

Chart(
                    data: _chartData,
                    variables: {
                      'x': Variable(
                        accessor: (Map map) => map['x'] as num,
                        scale:
                        LinearScale(min: -1, max: 1, formatter: (v) => ''),
                      ),
                      'y': Variable(
                        accessor: (Map map) => map['y'] as num,
                        scale:
                        LinearScale(min: -1, max: 1, formatter: (v) => ''),
                      ),
                      'type': Variable(
                        accessor: (Map map) => map['type'] as String,
                      ),
                    },
                    elements: [
                      LineElement(
                        shape: ShapeAttr(value: BasicLineShape()),
                        selected: {
                          'touchMove': {1}
                        },
                        color: ColorAttr(
                          variable: 'type',
                          values: [
                            const Color(0xff5470c6),
                            const Color(0xff91cc75),
                            const Color(0xff91cc75),
                            const Color(0xff91cc75),
                            const Color(0xff91cc75),
                            const Color(0xff91cc75),
                          ],
                        ),
                      )
                    ],
                    axes: [
                      Defaults.horizontalAxis,
                     // Defaults.verticalAxis,
                    ],
                    coord: RectCoord(color: Colors.white,
                        //verticalRange: [-1,1],
                      // horizontalRange: [-1,1]
                      ),
                    selections: {'choose': PointSelection(toggle: true)},
                    tooltip: TooltipGuide(
                      anchor: (_) => Offset.zero,
                     // align: Alignment.bottomRight,
                      multiTuples: true,
                    ),
                    annotations: [
                      MarkAnnotation(
                        relativePath:
                            Paths.circle(center: Offset.zero, radius: 270),
                        style: Paint()
                          ..color = Colors.blueGrey
                          ..strokeWidth = 1.0
                          ..style = PaintingStyle.stroke,
                        anchor: (size) => Offset(15+size.width/2, size.width/2-25),
                      ),
                      MarkAnnotation(
                        relativePath:
                            Paths.circle(center: Offset.zero, radius: 100),
                        style: Paint()
                          ..color = Colors.blueGrey
                          ..strokeWidth = 1.0
                          ..style = PaintingStyle.stroke,
                        anchor: (size) => Offset(15+size.width/2, size.width/2-25),
                      ),
                      MarkAnnotation(
                        relativePath:
                        Paths.circle(center: Offset.zero, radius: 230),
                        style: Paint()
                          ..color = Colors.blueGrey
                          ..strokeWidth = 0.5
                          ..style = PaintingStyle.stroke,
                        anchor: (size) => Offset(15+size.width/2, size.width/2-25),
                      ),
                /*
                      TagAnnotation(
                        label: Label(
                          'M',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width/2, size.width/2),
                      ),
                      */
                      TagAnnotation(
                        label: Label(
                          '0',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width - 10 * 2, 290),
                      ),
                      TagAnnotation(
                        label: Label(
                          '30',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width - 30 * 2, 140),
                      ),
                      TagAnnotation(
                        label: Label(
                          '60',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width - 80 * 2, 40),
                      ),
                      TagAnnotation(
                        label: Label(
                          '90',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width / 5 * 2+50, 0),
                      ),
                      TagAnnotation(
                        label: Label(
                          '120',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width-490, 40),
                      ),
                      TagAnnotation(
                        label: Label(
                          '150',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width-560, 140),
                      ),
                      TagAnnotation(
                        label: Label(
                          '180',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width - 610, 290),
                      ),
                      TagAnnotation(
                        label: Label(
                          '210',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width-560, 440),
                      ),
                      TagAnnotation(
                        label: Label(
                          '240',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width-470, 540),
                      ),
                      TagAnnotation(
                        label: Label(
                          '270',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width / 5 * 2+50, 580),
                      ),
                      TagAnnotation(
                        label: Label(
                          '300',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width - 80 * 2, 540),
                      ),
                      TagAnnotation(
                        label: Label(
                          '330',
                          LabelStyle(
                            style: TextStyle(
                                fontSize: 18,
                                color: Colors.black54
                            ),
                            align: Alignment.centerRight,
                          ),
                        ),
                        anchor: (size) => Offset(size.width - 30 * 2, 440),
                      ),
                    ],
                  )

**Comment by entronad** [comment]
It seems the color setting is OK, you can try add the position setting, it seems should be `Varset('x') * Varset('y') / Varset('type')`
https://pub.dev/documentation/graphic/latest/graphic/Varset-class.html

The dot of the circle grid can be set by the dash property of the grid strokeStyle:
 https://pub.dev/documentation/graphic/latest/graphic/StrokeStyle-class.html
