### ISSUE TITLE
Axis invertion

### ISSUE THREAD

**Issue by nico3587** [entronad/graphic#145]
Hi,

I would like to invert an axis, for exemple on a vertical axis have the minimum value on the top and the maximum value on the bottom. I've search a lot for doing this, but found nothing.
Is there a way for this ?

For this example, I would like to have on the vertical axis -10 on the top and 5 on the bottom.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/84204413/189096464-56bbfd46-cb09-417a-9898-00ef55c12e15.png">

Thanks for your help

**Comment by entronad** [comment]
You can either set the scale's min to 5, max to -10, or set coord's verticalRange to [1, 0], both will make the result top down
https://pub.dev/documentation/graphic/latest/graphic/ContinuousScale-class.html
https://pub.dev/documentation/graphic/latest/graphic/RectCoord-class.html
