### ISSUE TITLE
图表的elevation属性可以设置颜色吗

### ISSUE THREAD

**Issue by CoderUsing** [entronad/graphic#148]
elevation: SizeAttr(value: 0, updaters: {
          'choose': {true: (_) => 4}
        }),
我看到好像只能设置elavation的大小属性。

**Comment by CoderUsing** [comment]
图形边缘的颜色能定义吗，我看到我目前的阴影颜色都是灰色的

**Comment by entronad** [comment]
图形边缘的颜色就是指图形的颜色，或渐变色的平均值。你现在觉得都是灰色是视觉效果，阴影效果具体怎样表现是图形引擎决定的。你可以仔细观察示例App中的玫瑰图，或自己设个高一点的高阴影高度，是可以看出颜色的。

**Comment by CoderUsing** [comment]
好的，感谢

**Comment by iamiota** [comment]
<img width="286" alt="image" src="https://user-images.githubusercontent.com/7531576/203462346-b2f1c86d-85f3-4f2d-aaac-13be338b0f1c.png">

Thanks to the author for providing this open source library, awesome! I am currently trying to switch from `fl_chart` to `graphic`.
I tried the elevation attribute of graphic and it seems that it cannot be realized. I used the example app and there is no example with shadow. Is there any attribute that can realize shadow? thanks.

**Comment by entronad** [comment]
@iamiota 
This example is with elevation(shadow): https://github.com/entronad/graphic/blob/17c95ae68ae61f6e7feb2017ff25d838cf607000/example/lib/pages/interval.dart#L69

The elevation is different from shadow (like in web) indeed. Its effect relies on the implementation of the renderer(such as Flutter). If you want it more distinct, please set a higher value.
