### ISSUE TITLE
Zoom and move

### ISSUE THREAD

**Issue by KapitanPL** [entronad/graphic#152]
How to zoom the chart and move on the zoomed chart?

**Comment by entronad** [comment]
Check the updaters of coord: https://pub.dev/documentation/graphic/latest/graphic/RectCoord/horizontalRangeUpdater.html

There are some examples in the example app

**Comment by KapitanPL** [comment]
@entronad Thanks, that would definitely work. And I was sure I could manage it manually. However I hoped some more interactive way. Like pinching. Nevermind and thanks
