### ISSUE TITLE
chart点击事件的相关疑问

### ISSUE THREAD

**Issue by liumuchengyun** [entronad/graphic#154]
1. GestureType 是否会实现MoveUpdate响应？无需长按而移动更新。
2. CrosshairGuide 中 followPointer 设置为 [false, false] 时，长按点击移动时，十字光标存在延迟。
3. crosshair 支持在曲线图上标注点击时的数据点吗，可以注明点击时数据的位置。

**Comment by liumuchengyun** [comment]
elements 均为 LineElement。

**Comment by entronad** [comment]
1. 在 `on` 中设置，Flutter 手势类型中没有MoveUpdate，而是称为scaleUpdate，一指两指都用它
2. 那不是延迟，是它附着在数据点上
3. 目前不可以
