### ISSUE TITLE
如何在MarkAnnotation中给圆点添加border？

### ISSUE THREAD

**Issue by miaoyuxuan** [entronad/graphic#157]
你好，目前我已经通过使用MarkAnnotation添加了一个具有特定颜色的圆点，但是貌似没找到设置类似borderWidth和borderColor的属性，请问目前代码可以实现吗？

**Comment by entronad** [comment]
flutter 的图形都是不带border的，要实现类似border在上面再套一个中空的同形状

**Comment by miaoyuxuan** [comment]
已找到解决方案，感谢～
