### ISSUE TITLE
Missing points in polar plots

### ISSUE THREAD

**Issue by ignatz** [entronad/graphic#166]
Hey,

I'm having varying success with polar charts (There's a chance I'm holding it wrong). Let me provide a minimal example:

![Screenshot from 2022-11-27 15-28-38](https://user-images.githubusercontent.com/111986/204140613-88279031-1ece-427a-85cd-18478858dca9.png)

The latter 3 seem alright. However, I would expect the first two to show 1 and 2 sector segments, respectively.

I uploaded my minimal and executable example here: https://github.com/ignatz/flutter_graphic_polar_issue/blob/main/lib/main.dart#L42

**Comment by entronad** [comment]
Fixed in v2.0.3
now a tileCounts property is added to indicate the total counts in each dim when the data are too few to infer them.
