### ISSUE TITLE
Graph displaying weird Y label

### ISSUE THREAD

**Issue by xylim1119** [entronad/graphic#168]
Replicable with below data
[
                {'genre': '2022-09-24', 'sold': 67.7},
                {'genre': '2022-09-25', 'sold': 68.4},
                {'genre': '2022-10-08', 'sold': 67.5},
                {'genre': '2022-10-22', 'sold': 69.0},
]
![Screenshot 2022-12-01 at 1 59 04 PM](https://user-images.githubusercontent.com/94458484/204977357-16b9bd96-4c8d-4efc-a1c4-223aa0e6c6ce.png)

If i replace the 69.0 with 69.1 then everything is normal
[
                {'genre': '2022-09-24', 'sold': 67.7},
                {'genre': '2022-09-25', 'sold': 68.4},
                {'genre': '2022-10-08', 'sold': 67.5},
                {'genre': '2022-10-22', 'sold': 69.1},
]
![Screenshot 2022-12-01 at 2 00 07 PM](https://user-images.githubusercontent.com/94458484/204977439-161b575c-da57-422f-bf36-daa3fa346dbe.png)

is there any work around for this or is it a bug?

**Comment by entronad** [comment]
It seems a float precision problem of the nice number algorithm. Set a formatter for the ticks to cut the redundant decimals.

**Comment by xylim1119** [comment]
I'm sorry but that decimal is important for this graph representation.

**Comment by entronad** [comment]
I mean the "redundant decimals" caused by float precision problem, for example 69 becomes 69.0000000001. just keep 2 or 3 decimals for your need.

Float precision problem is common in programs, and the standard way to fix it is to cut the last positions of the decimals. The built-in algorithms should have this process, and I will check it. But now you can fix it for yourself for convenience.

**Comment by xylim1119** [comment]
[
{'genre': '2022-09-24', 'sold': 67.7},
{'genre': '2022-09-25', 'sold': 68.4},
{'genre': '2022-10-08', 'sold': 67.5},
{'genre': '2022-10-22', 'sold': 69.0},
]

This is my data how do i implement the fix you suggested?

**Comment by entronad** [comment]
I mean set https://pub.dev/documentation/graphic/latest/graphic/Scale/formatter.html to keep only one position of decimal

**Comment by xylim1119** [comment]
Thanks, it works by adding below inside the variable

scale: LinearScale(
  formatter: (v) => '${v.toStringAsFixed(2)}',
)),
