### ISSUE TITLE
Feature Request: Renko Charts

### ISSUE THREAD

**Issue by UNIcodeX** [entronad/graphic#171]
Great library!

Would it be possible to add support for renko charts with wicks?

**Comment by entronad** [comment]
This is a rather novel type of chart, I just learnt it by google.

The best feature of grammar of this lib is that it is not limited by certain types of charts, but composed by steps from data to graphics. So it's very flexible to custom your own graphics.

To this particular chart, You just need to extend your own Shape class, and I think it can be varied from a candlestick Shape, you can refer to this example: https://github.com/entronad/graphic/blob/17c95ae68ae61f6e7feb2017ff25d838cf607000/example/lib/pages/polygon_custom.dart#L736

**Comment by UNIcodeX** [comment]
Has renko chart type been added to this library or are you just closing this to clean up open tickets?
