### ISSUE TITLE
Candles overlapping with each other

### ISSUE THREAD

**Issue by loyaltytrooper** [entronad/graphic#172]
Hi entronad, when I am rendering candles in the candle stick charts, I am getting an overlapped render of the candles, 
1. any way to give them a margin or something so that they don't appear to be stacked.

2. Is there a way to make the candles a bit rounded from border

3. Any workaround to add line charts of a different object other than the data passed so that new objects can be passed instead of forcefully clubbing them in one

 Thank you!

**Comment by entronad** [comment]
1, 2: write your own Shape class, you can refer to the built-in candlestick Shape's code.
3: A chart only allows one data list, all graphics must based on the data. You can overlap two charts
