### ISSUE TITLE
多 Y 轴示例

### ISSUE THREAD

**Issue by simiwe** [entronad/graphic#180]
十分感谢提供这么优秀的开源项目。

请问本图表库可以实现类似 echarts 示例中的多 Y 轴示例吗？
刚开始接触 graphic ，看了几遍文档和示例代码，还是没有找到怎么实现多 Y 轴的思路。

https://echarts.apache.org/examples/zh/editor.html?c=multiple-y-axis&lang=js

![image](https://user-images.githubusercontent.com/902283/210084917-7c672de2-6825-4064-b9bf-5b7bb918f39b.png)

**Comment by fawdlstty** [comment]
只是为了实现这个功能，那有个方法，Stack一下，放两个Chart进去，一个y轴靠左一个y轴靠右，分别展示不同的数据，就行了

**Comment by simiwe** [comment]
明白了，感谢回复。

**Comment by entronad** [comment]
数据每一项结构类似
{
    date:
    ev:
    pr:
    te:
}
每个字段定义不同的variable，可以设置各自的scale
然后定义多个element，每个element在y维度上对应各自的variable。
可以设置多个axis，用position定义位置
