### ISSUE TITLE
How do I get 2 y axis ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [entronad/graphic#185]
How can I get 2 Y axis scales (one of the left, one on the right) ?

**Comment by entronad** [comment]
Define two axis guide, with position 0 and 1.

**Comment by TheCarpetMerchant** [comment]
Thanks ! I have two other questions :
- What's a tickline ?
- I have a TimeScale as horizontal axis, but the days are not aligned with the data. The labels occupy maximum space, while the actual graph has padding on the sides. How can I put the same padding on the scale so that its labels are aligned with the graph ?

**Comment by TheCarpetMerchant** [comment]
> Thanks ! I have two other questions :
> 
> * What's a tickline ?
> * I have a TimeScale as horizontal axis, but the days are not aligned with the data. The labels occupy maximum space, while the actual graph has padding on the sides. How can I put the same padding on the scale so that its labels are aligned with the graph ?
> 
> Edit : it's better with a picture. You can see that the days are aren't aligned with the bars. Should use a custom scale instead of a time one ? You'll also notice that the bars go across the white line, which doesn't happen if I remove `marginMin: 0`. ![image](https://user-images.githubusercontent.com/5080204/211653975-3b0293b2-05b1-40dc-9941-43bb819b467f.png)

Edit : It works fine by giving it the date ticks directly, so I'm pretty satisfied.
