### ISSUE TITLE
能否处理点击事件

### ISSUE THREAD

**Issue by shengzhaotong** [entronad/graphic#189]
这个库能不能像echarts那样处理点击事件，例如https://m.runoob.com/echarts/echarts-events.html，像这样点击数据项可以自定义行为

**Comment by entronad** [comment]
gesture channel for lower level: https://pub.dev/documentation/graphic/latest/graphic/Chart/gestureChannel.html
and selection channel for higher level: https://pub.dev/documentation/graphic/latest/graphic/Chart/gestureChannel.html

**Comment by shengzhaotong** [comment]
比如我想在图表中单击某一条数据后可以用一个自定义的弹窗或页面展示（或修改）数据，能否给出一个example，我没有找到在哪儿可以写自定义函数

**Comment by entronad** [comment]
接收到事件后，在图表外面的组件中添加弹窗或页面改变。相关逻辑用flutter的流控制方式：https://api.dart.dev/stable/2.19.0/dart-async/StreamController-class.html

**Comment by shengzhaotong** [comment]
我明白了，谢谢
