### ISSUE TITLE
y轴数据都为0时，显示负值如何处理？

### ISSUE THREAD

**Issue by codingpp** [entronad/graphic#191]
![20230208下午51038](https://user-images.githubusercontent.com/10908279/217485558-c17ca2f7-43ed-4d9d-aa16-ff7e11d634d4.jpg)
如图，如何将y轴数据从0开始？

**Comment by entronad** [comment]
设置scale的min

**Comment by codingpp** [comment]
scale: LinearScale(min: 0))
