### ISSUE TITLE
是否支持初始设置缩放比例

### ISSUE THREAD

**Issue by JDongKhan** [entronad/graphic#192]
您好，我这边有需求要显示很多数据，由于一屏显示不全需要水平滚动，查看了很多代码，水平滚动需要放大后才可以，是否能支持代码设置缩放比例，而不是手动放大。

**Comment by entronad** [comment]
RectCoord.horizontalRange
https://pub.dev/documentation/graphic/latest/graphic/RectCoord-class.html

**Comment by JDongKhan** [comment]
RectCoord.horizontalRange 不是设置范围的吗,它只能是 0 -1之间的范围。  而我想表达的是设置初始缩放系数，比如进来就将图表放大1.5倍。 这样数据多了也不显得拥挤，并拥有了滚动的能力。

**Comment by entronad** [comment]
设置[0, 1]时坐标系正好与显示区域一样大，可设置小于0-1（坐标系比显示区域小）或大于（坐标系比显示区域大）, 
你要的这种情况应该设置：[0, 1.5]，这样初始的时候坐标系就是显示区域的1.5倍，后面多出的0.5倍部分在可视区域外看不见，然后通过horizontalRangeUpdater可缩放
