### ISSUE TITLE
Widget name conflict with Flutter's View-widget

### ISSUE THREAD

**Issue by jluukka-ge** [entronad/graphic#193]
I've upgraded Flutter version from 3.3.10 to latest. Now I'm unable to use this library.

Flutter has introduced a new View-widget, whose name collides with the one defined in this library. The error originates from graphic-library's source.

I first encountered the problem when trying to build an APK of my app in an updated build environment. My app includes a simple line graph with minimal configuration. I would assume reproducing the problem should be as simple as trying to build any app which uses the graphic library with the latest version of Flutter. I'll try to verify this with a simple project in the near future.

Below is the error message produced by the failing build process.

```
Running Gradle task 'assembleRelease'...
[PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/developer/Android/sdk/platform-tools:/home/developer/flutter/bin, GLIBCPP_FORCE_NEW:1, OLDPWD:/home/tool/developer/src/android, FLUTTER_ROOT:/home/developer/flutter, ANDROID_SDK_ROOT:/home/developer/Android/sdk, GLIBCXX_FORCE_NEW:1, HOSTNAME:3ee417716c9a, FLUTTER_ALREADY_LOCKED:true, PWD:/home/tool/developer/src/android, HOME:/home/developer, SHLVL:1]
Checking the license for package Android SDK Build-Tools 29.0.2 in /home/developer/Android/sdk/licenses
License for package Android SDK Build-Tools 29.0.2 accepted.
Preparing "Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)".
"Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" ready.
Installing Android SDK Build-Tools 29.0.2 in /home/developer/Android/sdk/build-tools/29.0.2
"Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" complete.
"Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)" finished.
Checking the license for package Android SDK Platform 32 in /home/developer/Android/sdk/licenses
License for package Android SDK Platform 32 accepted.
Preparing "Install Android SDK Platform 32 (revision: 1)".
"Install Android SDK Platform 32 (revision: 1)" ready.
Installing Android SDK Platform 32 in /home/developer/Android/sdk/platforms/android-32
"Install Android SDK Platform 32 (revision: 1)" complete.
"Install Android SDK Platform 32 (revision: 1)" finished.
../../../developer/.pub-cache/hosted/pub.dev/graphic-1.0.1/lib/src/chart/chart.dart:22:1: Error: 'View' is imported from both 'package:flutter/src/widgets/view.dart' and 'package:graphic/src/chart/view.dart'.
import 'view.dart';
^^^^
../../../developer/.pub-cache/hosted/pub.dev/graphic-1.0.1/lib/src/chart/chart.dart:742:20: Error: 'View' is imported from both 'package:flutter/src/widgets/view.dart' and 'package:graphic/src/chart/view.dart'.
      state.view = View<D>(
                   ^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/home/developer/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1154

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/developer/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 9s
Running Gradle task 'assembleRelease'...                          190.0s
Gradle task assembleRelease failed with exit code 1

```

**Comment by entronad** [comment]
It seems OK in my case, I upgraded to Flutter 3.7.3 stable.
And I did't find View Widget in latest Flutter documents.

**Comment by IsaiChristian** [comment]
IM having the same issue with flutter 3.8 in the master channel, can you provide a workaround??

**Comment by entronad** [comment]
I will check the 3.8
(Why your Flutter version so new? I suggest you to use stable channel for production)

**Comment by h3ng3ll** [comment]
Hey guys , My flutter is  `Channel master, 3.8.0-4.0.pre,` I have similar issue and  solved it temporary .  It  was change in  the  _chart.dart_ code from 

_22_ ` import 'view.dart` to 
_22_ ` import view.dart as v` 

_189_ View<D>? view;
_189_ v.View<D>? view;

_748_ state.view = View<D>( 
_748_ state.view = v.View<D>(



after this operation  everything okay till I rebuild my dependencies this problem back again .  As I understand  conflict between libraries of dart and packages . What to do with that ?

**Comment by entronad** [comment]
I have fiexed it in v2.0.2 by changing the View to ChartView.

Still I an curious why you use a master channel of Flutter instead of stable or beta, would you tell me your consideration?

**Comment by IsaiChristian** [comment]
> (Why your Flutter version so new? I suggest you to use stable channel for production)

That was the right solution tbh,

**Comment by IsaiChristian** [comment]
> Still I an curious why you use a master channel of Flutter instead of stable or beta, would you tell me your consideration?

This was a bad call made earlier when we need it some fixes that were only live in master
