### ISSUE TITLE
Change the number of axis points to display.

### ISSUE THREAD

**Issue by vaibhavbhasin-ventura** [entronad/graphic#195]
Hi,
Is there any way to decide/change the number of X or Y axis points to display in a Line Chart. 

Use Case.

I want to display a 5 year chart but on Y Axis I am getting only 3 points.

Required : 2017 , 2018 , 2019 , 2020 , 2021
Currently : 2017 , 2019 , 2021 

So I want to show all points.

**Comment by entronad** [comment]
Scale.tickCount
https://pub.dev/documentation/graphic/latest/graphic/Scale/tickCount.html

**Comment by vaibhavbhasin-ventura** [comment]
Thanks, It worked.
