### ISSUE TITLE
dodge adjust index errror

### ISSUE THREAD

**Issue by yavuztarhan** [entronad/graphic#2]
three items have "0" index but shows 2 
const adjustData = [
  {"type": "Email", "index": 0, "value": 120},
  {"type": "Email", "index": 1, "value": 132},
  {"type": "Affiliate", "index": 0, "value": 220},
  {"type": "Affiliate", "index": 1, "value": 182},
  {"type": "Video", "index": 5, "value": 330},
  {"type": "Video", "index": 6, "value": 410},
  {"type": "Direct", "index": 5, "value": 330},
  {"type": "Direct", "index": 6, "value": 320},
  {"type": "Search", "index": 0, "value": 320},
  {"type": "Search", "index": 1, "value": 432},
];
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-07 at 11 04 42](https://user-images.githubusercontent.com/71377464/95304373-2c34c980-088d-11eb-912a-800978dbea7e.png)

**Comment by entronad** [comment]
Do you want the x axis to be 'type', and group each type by 'index'?
Could you please show me the whole props?
