### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by SuricateTrading** [entronad/graphic#205]
I get only like 5 FPS with a candlestick chart on web when scrolling. On Windows it works good.

[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.19044.2604], locale de-DE)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)         
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)              
    X cmdline-tools component is missing                                                      
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`                               
      See https://developer.android.com/studio/command-line for more details.                 
    X Android license status unknown.                                                         
      Run `flutter doctor --android-licenses` to accept the SDK licenses.                     
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web                                                              
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)                
[√] Android Studio (version 4.1)                                                              
[√] IntelliJ IDEA Community Edition (version 2022.3)                                          
[√] VS Code (version 1.63.2)                                                                  
[√] Connected device (3 available)                                                            
[√] HTTP Host Availability                                                                    
                                      
! Doctor found issues in 2 categories.

**Comment by entronad** [comment]
It seems OK in may web case (the example app).

How about try v2.0
