### ISSUE TITLE
Releases don`t follow semantic versioning

### ISSUE THREAD

**Issue by vbuberen** [entronad/graphic#209]
Latest `1.1.0` release had some breaking changes, which broke some projects (including the one I am working on). 

Such changes of API classes renaming should have incremented the package version to `2.0.0`.

Opening the issue in hope that in future versioning will follow the semantic versioning approach: https://semver.org/

**Comment by entronad** [comment]
Thanks for your advise, I readed the semver specs and know that I miss understand the minor version.

The term changes are backwards incompatible, so it should be a major version.

I have retracted v1.1.0 and published as v2.0.0
