### ISSUE TITLE
stacked line chart

### ISSUE THREAD

**Issue by bosiden** [entronad/graphic#214]
Hi,

Is it possible to achieve something like stacked line chart? I was able to create a simple chart with 1 line that gets updated dynamically over time, but I don't know if its possible to add two more lines to the same chart and have them updated individually? Think 3 different values of the same sensor that I want to plot under the same sensor chart.

**Comment by entronad** [comment]
It is possible.

Add three LineMark in the marks list property, in this case your datum should joint like `{'time': xx, 'sensor1': xx, 'sensor2': xx, 'sensor3':xx}`.

Or if time is not always the same, you datum could be like `{'time': xx, 'value': xx, 'sensor': 1}`, and group the data by variable 'sensor'.

In both cases, every time a data (no matter which sensor it from) updates, the whole chart will update, but the unchanged part will looks the same.

**Comment by bosiden** [comment]
Thanks! that worked.

There is one small issue tho. I have my datum set like {'time': xx, 'sensor1': xx, 'sensor2': xx, 'sensor3':xx},
sensor1 values range around 7-10, sensor2 values range around 0-2 and sensor3 values range around 0-1.

The values on the y-axis are auto adjusted fine if only sensor1 line chart is displayed, however if 2 or more line charts are displayed, the y-axis values are auto adjusted to only one of the sensors, ignoring the rest. This makes all 3 line charts appear overlapping and the y-axis auto adjusted range is not properly set to max/min of ALL 3 sensors data, but only one of them.

**Comment by bosiden** [comment]
I fixed it by using only one Linemark and have position adjust for 3 different types.
