### ISSUE TITLE
Child chart widget with tooltip triggers parent InkWell effect

### ISSUE THREAD

**Issue by muuyao** [entronad/graphic#215]
```dart
InkWell(
  onTap: () {
    print('Parent InkWell tapped');
  },
  child: Container(
    width: 200,
    height: 200,
    color: Colors.blue,
    alignment: Alignment.center,
    child: Chart(),
  ),
);
```
I would like to prevent the onTap event of the parent InkWell from being triggered when tapping on the chart widget. Could you please help me find a solution or guide me on how to achieve this behavior?

**Comment by entronad** [comment]
I remember there is a Flutter wrapper widget that can block gestures from passing to it's parent, you can wrap it between chart container and InkWell.

**Comment by muuyao** [comment]
```dart
GestureDetector(
      onTap: () {
        print('Child GestureDetector tapped');
      },
      behavior: HitTestBehavior.opaque,
      child: Chart(),
    ),
```
I use it like this, but it doesn't work

**Comment by entronad** [comment]
That won't work, behavior is not for this.
Try https://api.flutter.dev/flutter/widgets/AbsorbPointer-class.html or https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html
The rule of gestures passing between widgets is controlled by Flutter and can not be prevented from inside the chart
