### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by samuelxencov** [entronad/graphic#219]
where i can increase the font size of values of axis and y axis

**Comment by entronad** [comment]
1. https://pub.dev/documentation/graphic/latest/graphic/AxisGuide/label.html or https://pub.dev/documentation/graphic/latest/graphic/AxisGuide/labelMapper.html
2. There needs at least 2 points for a line chart, so avoid rendering the chart when data is not inited.

**Comment by samuelxencov** [comment]
am writting a code in flutter...do you orovide any example or written code

**Comment by samuelxencov** [comment]
where do i to put label in the code?
