### ISSUE TITLE
Candlestick hollow no longer dynamic

### ISSUE THREAD

**Issue by PalomarM97** [entronad/graphic#221]
Previously the  CandlestickShape hollow attribute could be decided for each candle, for example, 

in the version ^1.0.1 the code: 
```
shape: ShapeAttr(
   encoder: (tuple) => CandlestickShape(
      strokeWidth: 2.5,
      hollow: !(tuple['end'] <= tuple['start'])
   ),
),
```

would result in something like this:

![Simulator Screen Shot - iPhone 14 Pro - 2023-05-12 at 19 50 08](https://github.com/entronad/graphic/assets/109720397/3eb43d9c-fa92-4a46-990f-a44bf74c8afd)

now, in the latest version(^2.1.0) using the following code:

```
shape: ShapeEncode(
  encoder: (tuple) => CandlestickShape(
    hollow: !(tuple['end'] <= tuple['start']),
    strokeWidth: 5,
  ),
),
```

results in the following:

![image](https://github.com/entronad/graphic/assets/109720397/7e66df93-420b-47a3-8ba1-bf8f45ba572c)

![image_160](https://github.com/entronad/graphic/assets/109720397/9c6cfb5a-f92e-46b1-9989-685875983f7c)

It seems that now it only takes into account the first candle's values

**Comment by entronad** [comment]
Fixed in v2.2.0
