### ISSUE TITLE
Incompatibility with Flutter 3.10

### ISSUE THREAD

**Issue by lucavenir** [entronad/graphic#223]
Hi there,

Since the latest update (Flutter 3.10) I receive this error message at compile time.
```
Error: 'View' is imported from both 'package:flutter/src/widgets/view.dart' and 'package:graphic/src/chart/view.dart'.
```

This is happening because `view.dart` is indeed being imported from `flutter`, but this library also defines a file named `view.dart`.

I'm submitting a quick PR that should be a hotfix. This allows Flutter 3.10 code to be compatible with this library.

Let me know if that's ok.

**Comment by entronad** [comment]
There is no View class in Graphic since v2.0.2, try upgrade Graphic

**Comment by lucavenir** [comment]
Ok, this is weird, but for some reason after `flutter clean && flutter pub get && flutter pub upgrade` I was still seeing that class. It was also present in the main channel.

My bad, I now get no compilation errors. Thank you for your reply.
