### ISSUE TITLE
Labels ignore Chart padding

### ISSUE THREAD

**Issue by Reprevise** [entronad/graphic#226]
I have this simple line chart here and the x-axis labels appear to ignore the `padding` property set on the `Chart` widget. Is there anyway to get these labels to to match the width of the `RectCoord`?

![graphic line chart](https://github.com/entronad/graphic/assets/25782944/7066ebb9-e1a5-4fd8-ad84-c2bd0e74cde1)

**Comment by entronad** [comment]
The position of the first or last label anchor is inside the padding, if you want its label span  to be inside, you need to adjust manually, try set the offset of the labels by this property: https://pub.dev/documentation/graphic/latest/graphic/AxisGuide/labelMapper.html
