### ISSUE TITLE
How to set y-axis range manually?

### ISSUE THREAD

**Issue by sun-jiao** [entronad/graphic#237]
Hi there! I recently discovered this package and it looks amazing! However, I have a question. How can I manually set the range for the y-axis? For example, if the values are percentages, the y-axis should not expand beyond the range of 0 to 100. How can I restrict it to this range?

**Comment by entronad** [comment]
`LinearScale.min`, `LinearScale.max`

**Comment by sun-jiao** [comment]
@entronad thanks, I'll try it.
