### ISSUE TITLE
line Chart如何设置线条的头尾部为圆角呢？

### ISSUE THREAD

**Issue by BlazingCC** [entronad/graphic#248]
线性的Chart，line头尾部分是方形的，请问一下，如何配置可以让线条的头尾显示成圆角呢？
![202308171533](https://github.com/entronad/graphic/assets/22879023/f723c1f3-2320-45bf-ab36-68d1303c2568)

**Comment by entronad** [comment]
需要定制一下，shape现在默认使用的BasicLineShape类，你copy重写一下，按你的需要写一下style：
https://github.com/entronad/graphic/blob/e987cad6b06df8eddb295a439c4f40005412de5e/lib/src/shape/line.dart#L108C27-L108C27
然后用你写的这个shape
