### ISSUE TITLE
Different colors

### ISSUE THREAD

**Issue by SSebigo** [entronad/graphic#26]
For a rectangle interval chart, what is the idiomatic way to have different colors for bars?

For example, I have 5 bars and one should have a different color from the others, how to achieve that?

**Comment by entronad** [comment]
This example is in polar coordinate, but rectangle bars are just the same.
https://github.com/entronad/graphic/blob/514456f6401a223490721033f3b85995a173cf09/example/lib/pages/polar_interval.dart#L104

**Comment by SSebigo** [comment]
@entronad How does it use a String as an index for the colors list? (Sorry if it's a mistake)

**Comment by entronad** [comment]
There are two steps, the String variables are converted to index `int`s by [Scale](https://pub.dev/documentation/graphic/latest/graphic/Scale-class.html), and the index mapped to the colors list.
There is a detailed and full introduction:
https://medium.com/@entronad/the-versatility-of-the-grammar-of-graphics-d1366760424d

**Comment by SSebigo** [comment]
@entronad Is it possible a value that should never be displayed onscreen? So far from what I see the value used to index the color has to be "registered" inside ```Chart.variables```, the problem being that those values are displayed in the tooltip.

**Comment by SSebigo** [comment]
Nevermind, found out how to do it. Thx.
