### ISSUE TITLE
Feature request: LineChart (LineElement) show tooltip on hover over point and distinguish the line

### ISSUE THREAD

**Issue by milochadam** [entronad/graphic#27]
I would like to have a multi-line chart where points with data would be marked with dots or whatnot.
On hover over a point it would show label and data of the line and distinguish it (for example make the colour of the line line brighter or set to specific colour or make other lines more transparent).

Having a legend would also be nice though not as priority.

**Comment by entronad** [comment]
I think your requests can all be satisfied by now. Just need a little bit more complex specifications:
1. Line with dots: you just need to set both a `LineElement` and a `PointElement` in `elements` list, here is a similar line with area example: https://github.com/entronad/graphic/blob/a52806a187cb485d293defb7b1cfaf94c804165c/example/lib/pages/line_area.dart#L124
2. Custom your dots: inplement your own [PointShape](https://pub.dev/documentation/graphic/latest/graphic/PointShape-class.html) for the `shape` attribute, just like this example: https://github.com/entronad/graphic/blob/a52806a187cb485d293defb7b1cfaf94c804165c/example/lib/pages/custom.dart#L216
3. Legend: different people have different legend styles in mind, so we think it's not wise to provide a uniform legend component or define configurations for it. Instead, we encourage customizing the legend freely by [TagAnnotation](https://pub.dev/documentation/graphic/latest/graphic/TagAnnotation-class.html) and [MarkAnnotation](https://pub.dev/documentation/graphic/latest/graphic/MarkAnnotation-class.html), here is the legend example: https://github.com/entronad/graphic/blob/a52806a187cb485d293defb7b1cfaf94c804165c/example/lib/pages/custom.dart#L340
4. Tooltip: we provied a tooltip component [TooltipGuide](https://pub.dev/documentation/graphic/latest/graphic/TooltipGuide-class.html).

Your hover request is a little bit complex, it needs several steps:
1. Indicate by which variable you will group the data to get multi-lines. The indicating is implemented by `/` operator in the `position` algebra expression of all Elements.
1. Define a `PointSelection` which is triggered by hover gesture type. This selection's `variable` property should be the same as that you group the data. Then when you hover a dot, all data in the same group will be regarded as "selected", and other group datas as "unselected".
2. define there tag and color change in element's `onSelection` property.
Here is a similar but simpler example that may help: https://github.com/entronad/graphic/blob/a52806a187cb485d293defb7b1cfaf94c804165c/example/lib/pages/point.dart#L55

The specifications of this library need some efforts to learn. Please see details in the document and exaple app. But we promise it worth the efforts.

**Comment by milochadam** [comment]
It does what I want, thank you very much : )
