### ISSUE TITLE
Null check operator used on a null value on windows

### ISSUE THREAD

**Issue by mllw** [entronad/graphic#28]
════════ Exception caught by gesture library ═══════════════════════════════════
The following _CastError was thrown while dispatching a pointer event:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      _ChartState.build.<anonymous closure>
package:graphic/…/chart/chart.dart:633
#1      RenderPointerListener.handleEvent
package:flutter/…/rendering/proxy_box.dart:2888
#2      GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:420
#3      RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:278
#4      GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#5      GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338
#6      GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:296
#7      GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:279
#11     _invoke1 (dart:ui/hooks.dart:185:10)
#12     PlatformDispatcher._dispatchPointerDataPacket (dart

on line 666 should to recreate view
  bool shouldRelayout(covariant SingleChildLayoutDelegate oldDelegate) => state.view == null;

**Comment by entronad** [comment]
Please provide your chart specification.

**Comment by mllw** [comment]
SizedBox(
              width: 400,
              height: 400,
              child: Chart(
                rebuild: true,
                data: const [
                  {'genre': 'Sports', 'sold': 275},
                  {'genre': 'Strategy', 'sold': 115},
                  {'genre': 'Action', 'sold': 120},
                  {'genre': 'Shooter', 'sold': 350},
                  {'genre': 'Other', 'sold': 150},
                ],
                variables: {
                  'genre': Variable(
                    accessor: (Map map) => map['genre'] as String,
                  ),
                  'sold': Variable(
                    accessor: (Map map) => map['sold'] as num,
                  ),
                },
                elements: [LineElement()],
                axes: [
                  Defaults.horizontalAxis,
                  Defaults.verticalAxis,
                ],
              ),
            )

###########################################
pubspec.yaml

 graphic: ^0.6.0

**Comment by entronad** [comment]
What is your Flutter version?
Graphic 0.5 requires Flutter 2.4 and Graphic 0.6 requres Flutter 2.8.

**Comment by mllw** [comment]
environment:
  sdk: ">=2.14.4 <3.0.0"

[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19042.1348], locale zh-CN)

**Comment by entronad** [comment]
The bug dosen't seem to appear with the same specification.
Dose it still bother you?
