### ISSUE TITLE
Tool tip not working on iOS

### ISSUE THREAD

**Issue by Leoudayan** [entronad/graphic#291]
Hi,

I tried to use line_area_point chart for my project. Everything works well with android but for iOS the tool tip is not working. When I tap on the screen, nothing happens. If I do the same on android, it shows the tool tip. How to fix this issue?

**Comment by pamafe1976** [comment]
I has a similar issue, and found that it was relate to the PointerDeviceKind.touch in PointSelection.
Apparently, at least for the IOS simulator, it works with PointerDeviceKind.unknown

```
 'changePointer': PointSelection(
            nearest: true,
            on: {
              GestureType.longPressMoveUpdate,
              GestureType.tapDown,
              GestureType.scaleUpdate,
            },
            dim: Dim.x,
            devices: {PointerDeviceKind.touch},
          ),
```

**Comment by Leoudayan** [comment]
Hi @pamafe1976 many thanks for your reply. Where should I change this? I cant find this above code in the page I added the graph.

**Comment by Leoudayan** [comment]
@pamafe1976 Thanks bro! this helped me!
