### ISSUE TITLE
如何给 X 轴的首尾添加箭头？

### ISSUE THREAD

**Issue by GanZhiXiong** [entronad/graphic#294]
<img width="359" alt="image" src="https://github.com/entronad/graphic/assets/27394631/8f58a918-bf43-40bc-9b43-9cf8abd3f6f6">

X 轴首尾添加箭头，用于表示图表可左右滚动

**Comment by entronad** [comment]
用两个 https://pub.dev/documentation/graphic/latest/graphic/CustomAnnotation-class.html ，自行设定位置

**Comment by GanZhiXiong** [comment]
@entronad 
你终于回复了，我提了好几个 issues，不过目前我都已经解决了，但可能不是最优解。
你这个图表包，做得非常好，封装得很抽象，自定义很强大，而且支持缩放（其他图表包大都不支持缩放）。

**希望你能出些文档，让给你更多的人更容易参与进来贡献。**

**Comment by entronad** [comment]
@GanZhiXiong 
好的，谢谢你的建议，后面我会进一步充实文档
