### ISSUE TITLE
Questions whether few things are possible

### ISSUE THREAD

**Issue by lamarios** [entronad/graphic#295]
I've been looking around for graph library because fl_charts has some performance issues with what we try to accomplish (show tools tips in multiple graphs when highlighting one graph). This seem to be able to do that with the Gesture stream hence we might want to migrate to this library but from the docs, there are few things I can't seem to know if it is possible or not.

- Is it possible to draw zones like the red ones in the screenshot below ? ![Screenshot from 2024-04-26 16-07-27](https://github.com/entronad/graphic/assets/1192563/5325b46d-ec04-42c0-84bc-83e2cdc08db5)
- Is it possible to customize the tool tips to show the data of more than a single point ? ![Screenshot from 2024-04-26 16-07-47](https://github.com/entronad/graphic/assets/1192563/b932a896-001f-4ecd-b725-3b3ede82ed7d)

This library is looking great,
Thank you.

**Comment by entronad** [comment]
1. maybe this will help: https://pub.dev/documentation/graphic/latest/graphic/RegionAnnotation-class.html
2. you can rewrite the https://pub.dev/documentation/graphic/latest/graphic/TooltipGuide/renderer.html , there is a example of it in the example app.
