### ISSUE TITLE
Grpafico de barra com legenda na vertical

### ISSUE THREAD

**Issue by systemwtechnology** [entronad/graphic#298]
![image](https://github.com/entronad/graphic/assets/160787728/dd9d5a0d-3d2e-4c23-a15d-d15f91edb98d)

Não achei na documentação como deixar a legenda na vertical, caso tenham alguma solução só postar.

**Comment by entronad** [comment]
Esta biblioteca não oferece um componente predefinido de "legenda", pois as necessidades de personalização de legendas variam de pessoa para pessoa. Você pode usar os seguintes componentes para desenhar a sua própria legenda conforme necessário:

https://pub.dev/documentation/graphic/latest/graphic/CustomAnnotation-class.html
https://pub.dev/documentation/graphic/latest/graphic/TagAnnotation-class.html
