### ISSUE TITLE
[Question] Annotation on axis and move with crosshair?

### ISSUE THREAD

**Issue by dan12411** [entronad/graphic#299]
I have a question that is it possible to add annotation on axis and move with crosshair? Just like the yellow circle on the example image below.

Many thanks!

![line_chart](https://github.com/entronad/graphic/assets/21169170/39e27ffb-3d79-40ad-b344-338898ef7b5a)

**Comment by dan12411** [comment]
I found that it can archive by `selectionStream` & `annotations`, such as issue: #234.

What I have to do is using the annotations match the design I wanted.

But, next question will be show tooltip simultaneous?

[Screen_recording_20240702_165948.webm](https://github.com/entronad/graphic/assets/21169170/43c9132c-885a-4d0a-91b3-3f7842326eec)

**Comment by mstainer14** [comment]
@dan12411 

Can I ask how you managed to color some of your line red and some of your line green? I am trying to do the same but cannot achieve it.

Many thanks

**Comment by dan12411** [comment]
@mstainer14 

I create my custom `LineShape` which most of code comes from  `BasicLineShape`, and passing this shape in `LineMark` as below,

```dart
LineMark(
  ...
  shape: ShapeEncode<CustomLineShape>  // passing custom shape
)
```

The main logic to modify color will be code as below,

```dart
@override
  List<MarkElement> drawGroupPrimitives(
    ...
  ) {
    ...

    for (var contour in contours) {
      if (smooth) {
        ...
      } else {
        primitives.add(PolylineElement(points: contour, style: style));  // here!
      }
    }

    return primitives;
  }
```

But, in my case, it only works for the half of the height, it can't be cutting on any y position.

Need to optimized & find more flexible way to achieve it.

**Comment by mstainer14** [comment]
@dan12411 

Ahh okay, I understand. Thank you very much!

**Comment by mstainer14** [comment]
@dan12411,

Interesting, I will try on my project. Thanks again :smiley:
