### ISSUE TITLE
Multicolored line graph

### ISSUE THREAD

**Issue by mstainer14** [entronad/graphic#302]
Hi @entronad,

Thank you for creating an amazing graphing library for Flutter!

I am trying to create multi color line in the graph that will show a different color depending on a threshold value. Is this something that is possible with this library? I have not been able to achieve it so far.

Something that looks like the following:
![Screenshot from 2024-07-09 17-08-56](https://github.com/entronad/graphic/assets/5183197/233047aa-2cec-4a41-a3f7-8ed6ce6bc540)

For example, in the graph below in the between the two yellow horizontal markers, I'd like to make the line the same color.
![Screenshot from 2024-07-09 17-04-08](https://github.com/entronad/graphic/assets/5183197/d740de0a-0882-4b97-a25f-f535196fdb59)

Many thanks

**Comment by entronad** [comment]
This https://github.com/entronad/graphic/issues/299#issuecomment-2217981347 is the right answer, and if more complex, write your own custom shape https://github.com/entronad/graphic/issues/299#issuecomment-2217393297
