### ISSUE TITLE
如何正确的处理小数，小数显示会非常的奇怪

### ISSUE THREAD

**Issue by GanZhiXiong** [entronad/graphic#317]
数据：
``` dart
final timeSeriesSales1 = [
  TimeSeriesSales1(DateTime(2017, 9, 19), 28.3),
  TimeSeriesSales1(DateTime(2017, 9, 26), 28.4),
  TimeSeriesSales1(DateTime(2017, 10, 3), 28.4),
  TimeSeriesSales1(DateTime(2017, 10, 10), 28.2),
];
```
显示效果：
<img width="535" alt="image" src="https://github.com/user-attachments/assets/dbc596d0-1b5a-4a47-a8c7-528745befeaf">

<details>

<summary>chart 代码</summary>

```dart
Container(
  margin: const EdgeInsets.only(top: 10),
  width: 350,
  height: 300,
  child: Chart(
    data: timeSeriesSales1,
    variables: {
      'time': Variable(
        accessor: (TimeSeriesSales1 datum) => datum.time,
        scale: TimeScale(
          formatter: (time) => _monthDayFormat.format(time),
        ),
      ),
      'sales': Variable(
        accessor: (TimeSeriesSales1 datum) => datum.sales,
      ),
    },
    marks: [
      LineMark(
        shape: ShapeEncode(value: BasicLineShape(dash: [5, 2])),
        selected: {
          'touchMove': {1}
        },
      )
    ],
    coord: RectCoord(color: const Color(0xffdddddd)),
    axes: [
      Defaults.horizontalAxis,
      Defaults.verticalAxis,
    ],
    selections: {
      'touchMove': PointSelection(
        on: {
          GestureType.scaleUpdate,
          GestureType.tapDown,
          GestureType.longPressMoveUpdate
        },
        dim: Dim.x,
      )
    },
    tooltip: TooltipGuide(
      followPointer: [false, true],
      align: Alignment.topLeft,
      offset: const Offset(-20, -20),
    ),
    crosshair: CrosshairGuide(followPointer: [false, true]),
  ),
)
```

</details>

**Comment by GanZhiXiong** [comment]
@entronad  @dan12411
我添加了如下代码，格式化了 Y 轴，这样 Y轴的值不会溢出屏幕。
但是有两个 28.3，并且 28.4 的坐标没有在 28.4 那条 Y轴横向上。

<img width="535" alt="image" src="https://github.com/user-attachments/assets/5c3c53c1-bfa6-4d53-b0f3-0e6515d34a6d">

**Comment by GanZhiXiong** [comment]
我发现将 LinearScale 的 niceRange 设置为 true，可以解决此问题。
![image](https://github.com/user-attachments/assets/1691715e-b3db-4f33-9abf-da870242c71f)

**Comment by GanZhiXiong** [comment]
但是什么niceRange 在什么时候设置为 true 比较合适呢？
代码注释并没有明确说明：
```dart
  /// Whether to extend the [min] and [max] to get nice round values.
  bool? niceRange;
``` 

我又做了个对比，下图左边图表niceRange 设置为true，右边设置为 false。
![image](https://github.com/user-attachments/assets/25fc1dfd-751f-4182-ab3b-f815a845b2e1)

**Comment by GanZhiXiong** [comment]
感觉与 niceRange 无关，比如如下数据，28.8 的坐标点，并没有在 Y轴 28.8 那条线上，原因应该与 `formatter` 有关。
```dart
formatter: (value) {
  return NumberFormat('#.#').format(value);
}

final timeSeriesSales2 = [
  TimeSeriesSales1(DateTime(2017, 9, 19), 28.7),
  TimeSeriesSales1(DateTime(2017, 9, 26), 28.7),
  TimeSeriesSales1(DateTime(2017, 10, 3), 28.8),
  TimeSeriesSales1(DateTime(2017, 10, 5), 28.8),
  TimeSeriesSales1(DateTime(2017, 10, 7), 28.8),
  TimeSeriesSales1(DateTime(2017, 10, 10), 28.2),
  TimeSeriesSales1(DateTime(2017, 10, 12), 28.2),
];
```
![image](https://github.com/user-attachments/assets/f9544d3f-ee36-4ef6-8748-bdc779936147)

我去掉 formatter 代码后，看起来正常了。
<img width="367" alt="image" src="https://github.com/user-attachments/assets/2b374bad-bad5-4a5c-8f33-63e72b18fe9c">

**Comment by entronad** [comment]
你好，这个问题是这样的：
到底显示哪些 tick 是一个复杂的问题，称之为 nice number 算法，我这里和绝大多数图表库一样，采用的是Wilkinson的算法。
既然是计算的，就有可能出现浮点数精度问题，由于浮点数处理要求不一，因此没有内置，你这里用 format 是可以的，出现两个28.3应该是四舍五入撞一起了。
如对tick有特殊要求可直接通过ticks参数直接给出你要的值数组。

**Comment by GanZhiXiong** [comment]
> @entronad @dan12411 但是niceRange 在什么时候设置为 true 比较合适呢？ 代码注释并没有明确说明。能不能自动根据数据设置合适的 ncieRange？
> 
> ```dart
>   /// Whether to extend the [min] and [max] to get nice round values.
>   bool? niceRange;
> ```
> 
> 我又做了个对比，下图左边图表niceRange 设置为true，右边设置为 false。我感觉右边好点。 ![image](https://private-user-images.githubusercontent.com/27394631/366259816-25fc1dfd-751f-4182-ab3b-f815a845b2e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMTY3MTUsIm5iZiI6MTcyNjAxNjQxNSwicGF0aCI6Ii8yNzM5NDYzMS8zNjYyNTk4MTYtMjVmYzFkZmQtNzUxZi00MTgyLWFiM2ItZjgxNWE4NDViMmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAxMDAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTI2Y2UzZGM0ZGFkMTVlNDc1NWM1YmNkYWRmODQ4NWIxZjVhN2IxNTBhNzg2NjZjNzI5YjhkMWVhNjRlM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vc_n5iMuE7V-dBF53mBJz78UxnWI0XtkOmEjdRa-4ek)

1. 是不是 `niceRange` 设置为 true 就表示采用的是Wilkinson的算法？
2. niceRange 默认为 null，在什么场景在设置为 true 比较合适呢？
3. 我发现好像 niceRange 设置为 true，坐标点是在 Y轴刻度内的。

**Comment by GanZhiXiong** [comment]
明白了，感谢你的回复！
