### ISSUE TITLE
Testing tooltips

### ISSUE THREAD

**Issue by sprimm98** [entronad/graphic#318]
Hi, thanks for your work on this package. I'd like to test whether the tooltip of a chart is triggered on tap and, ideally, if certain text is visible then. Is this possible? Thanks in advance.

**Comment by entronad** [comment]
Yes. please see this doc:
https://pub.dev/documentation/graphic/latest/graphic/TooltipGuide-class.html
and this example app:
https://github.com/entronad/graphic/tree/main/example
