### ISSUE TITLE
请问如何正确构造数据 Expected a value of type '(dynamic) => dynamic', but got one of type '(Map<dynamic, dynamic>) => String'

### ISSUE THREAD

**Issue by zjyhll** [entronad/graphic#36]
![image](https://user-images.githubusercontent.com/8895877/147198521-37fabf16-6de7-453d-8c0e-79c9899020e9.png)
我这边会出现这种情况
Expected a value of type '(dynamic) => dynamic', but got one of type '(Map<dynamic, dynamic>) => String'
json数据没有问题
![image](https://user-images.githubusercontent.com/8895877/147198683-6f411a71-a024-44fe-96bc-1fb3aca866f7.png)
大概是这样
[{
	time: 2021 - 11 - 29 15: 00,
	name: 空气温度(℃),
	value: 20.1
}, {
	time: 2021 - 11 - 29 15: 20,
	name: 空气温度(℃),
	value: 20.1
}]

**Comment by entronad** [comment]
你把variables的定义那段贴上来看下

**Comment by jiangweihu** [comment]
请问你这里解决了吗 我应该如何使用accessor来从数据中获取变量? 我定义了一个list<Map>类型 List listXY = [
  {'x': 1, 'y': 11},
  {'x': 2, 'y': 22},
  {'x': 3, 'y': 33},
  {'x': 4, 'y': 44},
  {'x': 5, 'y': 55}
];
使用时通过accessor: (List<Map> list) => list[0]['x'] as num
报错:type '(List<Map<Object, Object>>) => num' is not a subtype of type '(Object) => dynamic'
请问我应该如何处理

**Comment by entronad** [comment]
@jiangweihu 
accessor 是针对数据项的，你这个应该是 (Map<String, num> m) => m['x']

另外建议尽可能把泛型写全

**Comment by jiangweihu** [comment]
> @jiangweihu accessor 是针对数据项的，你这个应该是 (Map<String, num> m) => m['x']
> 
> 另外建议尽可能把泛型写全

感谢回答 如果我这么写 accessorr在断言的时候会报
accessor is Accessor<D, String> || accessor is Accessor<D, num> || accessor is Accessor<D, DateTime>': is not true.
如果我加上 (Map<String, num> m) => m['x'] as num 则又会报和之前一样的错误
请问我应该如何把我的数据引用进来 第一次接触编程开发 不太理解这里accessor的写法 感谢回答

**Comment by jiangweihu** [comment]
> @jiangweihu accessor 是针对数据项的，你这个应该是 (Map<String, num> m) => m['x']
> 
> 另外建议尽可能把泛型写全

我看了G2的语法和example中的data数据 发现基本都是const定义的常量 对于这种list变量我应该如何处理

**Comment by jiangweihu** [comment]
> 

我的理解Accessor<D, V> accessor D是指我的listXY中的数据类型也就是{'x': 1, 'y': 11}, V是我的值也就是1和11

**Comment by entronad** [comment]
这个理解是对的，
as num 要加上，可以参考 example 里的泛型设定

**Comment by jiangweihu** [comment]
> 这个理解是对的， as num 要加上，可以参考 example 里的泛型设定

感谢回答 我再继续研究一下
