### ISSUE TITLE
Add RangeSignal to assist with async data loading

### ISSUE THREAD

**Issue by tlvenn** [entronad/graphic#39]
Loading data asynchronously is useful when there is huge dataset and we simply cant load it all. Right now it seems like Graphic is not providing the signal that would permit the app to detect that we are touching the boundary of the loaded data and that we actually need to fetch more.

When the "range" (not sure about the right terminology) is changing (basically moving along the X axis), it would be useful to emit a signal that the app can use to load more data if needed.

**Comment by tlvenn** [comment]
It might be useful to provide a default loading Animation that can be customized with a `showLoading` & `hideLoading` similarly to what ECharts is providing in this regard.
> https://echarts.apache.org/en/api.html#echartsInstance.showLoading
> https://echarts.apache.org/en/api.html#echartsInstance.hideLoading

**Comment by entronad** [comment]
Thanks for your advice.
Loading big data asynchronously is also an important feature we are working on it.

In the beginning, Flutter is only for mobile, so the big data and facets are not critically needed features(We know mobile devices have small screens). But now Flutter apps may be web or desktop, so these features are on the schedule now.

**Comment by tlvenn** [comment]
Do you happen to have a rough timeline on when you will be able to push this ? Are you going with the direction on creating a `Signal` as I suggested or do you have something else in mind ?

Thanks !

**Comment by tlvenn** [comment]
Digging a bit in the code, it seems that this is actually already possible. The `RectCoord` already has `onVerticalRangeSignal` and `onHorizontalRangeSignal`.

It seems I can wrap the default range updater and trigger an event on my own.

**Comment by entronad** [comment]
There is a complete signal system in the chart now, which handles gesture, resize, and data change signals.
But it is now only for internal usage. The real user callback channel for these signals will be exposed in the future, only after we evaluated that they will not be abused.

Mean while there are some update functions which will be called on these signals. They should be pure function, but as you find, you can hack them for something else. But be careful that may interrupt the rendering flow.

**Comment by tlvenn** [comment]
I get what you are saying, definitively a temporary hack until those signals are emitted / exposed to the end user.

**Comment by entronad** [comment]
In version 0.9.0, we add Interaction Channels for users to input or subscribe signals and selections.
It is in form of StreamController, which is better than callbacks.
See details in:
https://pub.dev/documentation/graphic/latest/graphic/Chart/gestureChannel.html
https://pub.dev/documentation/graphic/latest/graphic/GeomElement/selectionChannel.html
