### ISSUE TITLE
Candle

### ISSUE THREAD

**Issue by m2faridi** [entronad/graphic#4]
please add candle

**Comment by entronad** [comment]
candlestick chart is a highly professional financial chart, witch now can not bee expressed by grammar of graphics.
So we removed it. In fact, the candlestick chart in version 0.1.0 is too crude to use.
You can find alternatives in these searching results: https://pub.dev/packages?q=candlestick

**Comment by m2faridi** [comment]
No I need to combine several diagrams, one of which is a candlestick diagram and this library is not good for me

**Comment by m2faridi** [comment]
Please add very practical and great

**Comment by entronad** [comment]
Then you can use a custom shape for a schema geom.
I will add an example later.

**Comment by entronad** [comment]
Here is the example:
https://github.com/entronad/graphic/blob/43d020e33fd536074f732ba53afcb4da9e0a15f1/example/lib/pages/custom_shape_page.dart#L52

**Comment by m2faridi** [comment]
thanks
