### ISSUE TITLE
Labels truncated when flipped with Y axis set on the right

### ISSUE THREAD

**Issue by tlvenn** [entronad/graphic#40]
I am experimenting with placing the Y axis on the right and flipping the labels as mentioned in #38
```
AxisGuide(
    position: 1,
    flip: true,
    label: LabelStyle(
      Defaults.textStyle,
      offset: Offset(0, 0),
    ),
    grid: Defaults.strokeStyle,
  )
```
![image](https://user-images.githubusercontent.com/3340262/148022442-5d4bd7b0-a48e-4164-b0be-5949d45420c4.png)

It seems the graph boundaries are not computed properly to allow room for the labels in that scenario.

**Comment by entronad** [comment]
The space between the coordinate region and the chart boundary is called `padding`, just like in the CSS box model.

There is no AI magic in the padding calculation. They are just set by `Chart.padding`, with a default `EdgeInsets.fromLTRB(40, 5, 10, 20)`. So if the labels are cut, just set another value to adjust.

Yet there is still a good news, `padding` property is a function of chart `size`, so you can do some responsive design in the setting.

**Comment by tlvenn** [comment]
Ha great, I was not sure this was 100% handled with the padding, makes total sense.
