### ISSUE TITLE
Does this library support zooming?

### ISSUE THREAD

**Issue by Ujas-Majithiya** [entronad/graphic#42]
Hello , first thank you for this awesome library.

I was checking the example app and as for my use case I need pan and zooming feature in my app. And by digging some documentation and some internal code I found this two getters `horizontalRangeSignal` and `verticalRangeSignal` which's documentation says `A signal update for scaling and panning` for respective coordinates.

So I think which can be used in zooming so I tried putting them in `RectCoord()` in `coord` property but nothing happens so am doing anything wrong here.

I am putting this in Timeline chart of example app just like this,
```
Container(
                margin: const EdgeInsets.only(top: 10),
                width: 350,
                height: 300,
                child: Chart(
                  data: timeSeriesSales,
                  variables: {
                    'time': Variable(
                      accessor: (TimeSeriesSales datum) => datum.time,
                      scale: TimeScale(
                        formatter: (time) => _monthDayFormat.format(time),
                      ),
                    ),
                    'sales': Variable(
                      accessor: (TimeSeriesSales datum) => datum.sales,
                    ),
                  },
                  elements: [
                    LineElement(
                        shape: ShapeAttr(value: BasicLineShape(dash: [5, 2])))
                  ],
                  axes: [
                    Defaults.horizontalAxis,
                    Defaults.verticalAxis,
                  ],
                  selections: {
                    'touchMove': PointSelection(
                      on: {
                        GestureType.scaleStart,
                        GestureType.scaleUpdate
                      },
                      dim: Dim.x,
                    )
                  },
                  coord: RectCoord(
                    onHorizontalRangeSignal: Defaults.horizontalRangeSignal,  // <--------------- here
                    onVerticalRangeSignal: Defaults.verticalRangeSignal,
                  ),
                  tooltip: TooltipGuide(
                    followPointer: [false, true],
                    align: Alignment.topLeft,
                    offset: const Offset(-20, -20),
                  ),
                  crosshair: CrosshairGuide(followPointer: [false, true]),
                ),
              ),
```

So now the title does it support zooming?

**Comment by karniv00l** [comment]
I've also come across this package today. Great stuff!

You can see working Pan & Zoom in `Point Element -> Interactive Scatter Chart`.

However, I see some small issues (tested on macOS and android devices):

- on mobile: sometimes panning doesn't work, looks like it's confusing scrolling and panning
- on desktop: it's doing both scrolling and zooming with the mouse wheel
- zooming on both platforms feels either too slow (mobile) or too fast (desktop mouse wheel)

**Comment by entronad** [comment]
@Ujas-Majithiya 
your specification seems OK.
First make sure the Graphic version is at least 0.7.0, there's a bug before. than as @karniv00l check whether the Interactive Scatter Chart example works fine.
Then is your outer widget scrollable? the scrolling may compete with the gestures.

**Comment by entronad** [comment]
@karniv00l 
Thanks for your attention.
1. In Graphic charts, the gesture system is a part of the app's gesture arena system, which means scrolling and panning do "compete" with each other and only one can "win". This arena rule proposed by google is different from web, but I agree it is more scientific. See details in: https://docs.flutter.dev/development/ui/advanced/gestures#gesture-disambiguation.
2. The signal handler functions are totally customizable, `Defaults.horizontalRangeSignal` is only for easy usage. You can copy and modify the default function to create your own.
3. As your second question, in the handler function, the signal param's gesture payload contains the device information. So your can define whether to zoom in mobile or desktop.
4. As your third question, the react coefficient can be adjusted in your custom handler functions.

**Comment by ujas-m-simformsolutions** [comment]
@entronad yes that was scrolling issue it works on interactive scatter chart thank you for your insight about gestures

**Comment by Ujas-Majithiya** [comment]
@entronad yes that was scrolling issue it works on interactive scatter chart thank you for your insight about gestures
