### ISSUE TITLE
Perform task when tap/click on a chart window.

### ISSUE THREAD

**Issue by drmirk** [entronad/graphic#44]
I am showing multiple charts using column. When user clicks/taps on a chart window. I need to perform some specific task. I tried with gesture detector as chart parent widget. But gesture detector is not detecting any gesture. 
Can you please help me solve this?

**Comment by entronad** [comment]
In Flutter gesture arena system, only one detector can capture a gesture at one time. The chart is part of the arena system, so the above charts "win" their parent widget in the arena.
The solution is try to ignore the chart widget: https://stackoverflow.com/questions/50600747/flutter-ignore-touch-events-on-a-widget

**Comment by drmirk** [comment]
Thank you so, so much for your quick reply, and for the suggestion. I just solved my issue. Thank you very much, really appreciate it.
