### ISSUE TITLE
Tootltip title

### ISSUE THREAD

**Issue by ZdenekKrcal** [entronad/graphic#49]
How to add title to the tooltip and colorful dots for recognizing values something like legend in tooltip. And add own title for values in tooltip.

**Comment by entronad** [comment]
Custom your own `TooltipGuide.renderer`, here's an example:
https://github.com/entronad/graphic/blob/d09de163ad642b23f5b0840ef234a2d946a4d005/example/lib/pages/custom.dart#L51
