### ISSUE TITLE
how to show tooltip when tap down

### ISSUE THREAD

**Issue by Yonkers** [entronad/graphic#5]

**Comment by entronad** [comment]
Tooltip has not been implemented yet. It may come few months later.

**Comment by guenth39** [comment]
Would love to see that! Unfortunately the package is useless for me without this feature. 
Do you have a hint where to start with an implementation? I already played around with the `ChartInteraction` callback. With a Stack you can add Information above the Chart but isn't as good as an integration in the Package. As well, I don't know how to align the tooltip to a data point without implementing it in the package.

**Comment by Rocky49** [comment]
How to add label on the bar or funnel?
