### ISSUE TITLE
performance problem with a lot of data

### ISSUE THREAD

**Issue by ZdenekKrcal** [entronad/graphic#51]
Hi, it is great library, but I have problem with performance. I have classic line chart with a lot of data. But chart is too slow, i cant zoom because it is not possible. I'm trying it on the web.

Config:

```dart

selections: {
              'tooltipMouse': PointSelection(
                on: {
                  GestureType.hover,
                },
                devices: {PointerDeviceKind.mouse},
                variable: 'Datum',
                dim: Dim.x,
              ),
              'tooltipTouch': PointSelection(
                on: {
                  GestureType.scaleUpdate,
                  GestureType.tapDown,
                  GestureType.longPressMoveUpdate
                },
                devices: {PointerDeviceKind.touch},
                variable: 'Datum',
                dim: Dim.x,
              ),
            },
coord: RectCoord(
              horizontalRangeUpdater: Defaults.horizontalRangeSignal,
            ),
data: _data,
            variables: {
              'Datum': Variable(
                accessor: (Map datum) => datum['Datum'] as String,
                scale: OrdinalScale(),
              ),
              'Hodnota': Variable(
                accessor: (Map datum) => datum['Hodnota'] as num,
                scale: LinearScale(),
              ),
              'Skupina': Variable(
                accessor: (Map datum) => datum['Skupina'] as String,
                scale: OrdinalScale(),
              ),
            },
            elements: [
              LineElement(
                position:
                    Varset('Datum') * Varset('Hodnota') / Varset('Skupina'),
                color: ColorAttr(
                  variable: 'Skupina',
                  values: [
                    const Color.fromARGB(255, 0, 236, 0),
                    const Color.fromARGB(255, 0, 128, 255),
                    const Color.fromARGB(255, 192, 192, 192),
                  ],
                ),
              ),
            ],
            axes: [
              Defaults.horizontalAxis,
              Defaults.verticalAxis,
            ],
```

**Comment by entronad** [comment]
How many data items?

**Comment by ZdenekKrcal** [comment]
> How many data items?

About 723 000 records.

**Comment by entronad** [comment]
2000 records is a rather small set, in fact there is a well performed chart in the example app of 20000 records.

I noticed you want a horizontal zoom, But did you put the chart in a scrollable wrapper widget? the scrollable wrapper may compete with the chart in the gesture arena and take many of the gestures, which makes you feel "hard" to zoom.

**Comment by ZdenekKrcal** [comment]
> 2000 records is a rather small set, in fact there is a well performed chart in the example app of 20000 records.
> 
> I noticed you want a horizontal zoom, But did you put the chart in a scrollable wrapper widget? the scrollable wrapper may compete with the chart in the gesture arena and take many of the gestures, which makes you feel "hard" to zoom.

It is about 2169 records and I will place code of page where is component with chart and after that i will place code of component.

There is a short video of behaving of chart:

https://webrent.cz/chart/

```dart
class HistoryBidAskPage extends StatelessWidget {
  static const routeName = 'historyBidAsk';

  final int contractId;

  const HistoryBidAskPage({
    Key? key,
    required this.contractId,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final _contractProvider =
        Provider.of<ContractProvider>(context, listen: false);

    final Contract? _contract = _contractProvider.getContract(contractId);

    // print(_contract.tickerSymbol);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Ask, Bid, Vývoj Settlement'),
        centerTitle: true,
      ),
      body: FutureBuilder<void>(
          future: _contractProvider.fetchBidAskHistory(_contract?.tickerSymbol),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(
                child: CircularProgressIndicator(
                  valueColor: AlwaysStoppedAnimation(BrandColors.blue),
                ),
              );
            }

            if (snapshot.hasError) {
              return Center(
                child: Text('${snapshot.error}'),
              );
            }

            return HistoryBidAskChart(
              items: _contractProvider.bidAskHistoryData,
              contractName: _contract?.contractName,
            );
          }),
    );
  }
}

```

Here is HistoryBidAskChart:

```dart

class HistoryBidAskChart extends StatefulWidget {
  const HistoryBidAskChart({Key? key, this.items, this.contractName})
      : super(key: key);

  final List<BidAskHistory>? items;
  final String? contractName;

  @override
  _HistoryBidAskChartState createState() => _HistoryBidAskChartState();
}

class _HistoryBidAskChartState extends State<HistoryBidAskChart> {
  final List<Map<String, dynamic>> _data = [];

  @override
  void initState() {
    super.initState();

    for (var item in widget.items!) {
      _data.add({
        'Datum': item.formateDate,
        'Hodnota': item.ask,
        'Skupina': 'Ask',
      });
      _data.add({
        'Datum': item.formateDate,
        'Hodnota': item.bid,
        'Skupina': 'Bid',
      });
      _data.add({
        'Datum': item.formateDate,
        'Hodnota': item.settlement,
        'Skupina': 'Settlement',
      });
    }

    print(_data.length);
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(
          widget.contractName ?? '',
          style: Theme.of(context).textTheme.headline6,
        ),
        Expanded(
          child: Chart(
            data: _data,
            variables: {
              'Datum': Variable(
                accessor: (Map datum) => datum['Datum'] as String,
                scale: OrdinalScale(),
              ),
              'Hodnota': Variable(
                accessor: (Map datum) => datum['Hodnota'] as num,
                scale: LinearScale(),
              ),
              'Skupina': Variable(
                accessor: (Map datum) => datum['Skupina'] as String,
                scale: OrdinalScale(),
              ),
            },
            elements: [
              LineElement(
                position:
                    Varset('Datum') * Varset('Hodnota') / Varset('Skupina'),
                color: ColorAttr(
                  variable: 'Skupina',
                  values: [
                    const Color.fromARGB(255, 0, 236, 0),
                    const Color.fromARGB(255, 0, 128, 255),
                    const Color.fromARGB(255, 192, 192, 192),
                  ],
                ),
              ),
            ],
            axes: [
              Defaults.horizontalAxis,
              Defaults.verticalAxis,
            ],
            selections: {
              'tooltipMouse': PointSelection(
                on: {
                  GestureType.hover,
                },
                devices: {PointerDeviceKind.mouse},
                variable: 'Datum',
                dim: Dim.x,
              ),
              'tooltipTouch': PointSelection(
                on: {
                  GestureType.scaleUpdate,
                  GestureType.tapDown,
                  GestureType.longPressMoveUpdate
                },
                devices: {PointerDeviceKind.touch},
                variable: 'Datum',
                dim: Dim.x,
              ),
            },
            tooltip: TooltipGuide(
              followPointer: [true, true],
              align: Alignment.topLeft,
              variables: ['Skupina', 'Hodnota'],
            ),
            crosshair: CrosshairGuide(
              followPointer: [true, false],
            ),
            coord: RectCoord(
              horizontalRangeUpdater: Defaults.horizontalRangeSignal,
            ),
            annotations: [
              MarkAnnotation(
                relativePath: Path()
                  ..addRect(
                      Rect.fromCircle(center: const Offset(0, 0), radius: 5)),
                style: Paint()..color = const Color.fromARGB(255, 0, 236, 0),
                anchor: (size) => const Offset(30, 20),
              ),
              TagAnnotation(
                label: Label(
                  'Ask',
                  LabelStyle(
                    align: Alignment.centerRight,
                    style: const TextStyle(fontSize: 16),
                  ),
                ),
                anchor: (size) => const Offset(40, 20),
              ),
              MarkAnnotation(
                relativePath: Path()
                  ..addRect(
                      Rect.fromCircle(center: const Offset(0, 0), radius: 5)),
                style: Paint()..color = const Color.fromARGB(255, 0, 128, 255),
                anchor: (size) => const Offset(80, 20),
              ),
              TagAnnotation(
                label: Label(
                  'Bid',
                  LabelStyle(
                    align: Alignment.centerRight,
                    style: const TextStyle(fontSize: 16),
                  ),
                ),
                anchor: (size) => const Offset(90, 20),
              ),
              MarkAnnotation(
                relativePath: Path()
                  ..addRect(
                      Rect.fromCircle(center: const Offset(0, 0), radius: 5)),
                style: Paint()
                  ..color = const Color.fromARGB(255, 192, 192, 192),
                anchor: (size) => const Offset(130, 20),
              ),
              TagAnnotation(
                label: Label(
                  'Settlement',
                  LabelStyle(
                    align: Alignment.centerRight,
                    style: const TextStyle(fontSize: 16),
                  ),
                ),
                anchor: (size) => const Offset(140, 20),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

```

**Comment by entronad** [comment]
I have find the problem: You didn't indicate the tick count for 'Datum' variable, so each point has a tick label that there are too many labels. If you look below the x axis carefully, there is a "thick bar", that's 2000 text labels stack together.
The default tick count for ordinal scale is the same as data count, that's for convenience. You should indicate it for big data cases:
```
'Datum': Variable(
  accessor: (Map datum) => datum['Datum'] as String,
  scale: OrdinalScale(tickCount: 5),
),
```

You know, painting thousands of points is an easy task, but layout thousands of text paragraphs is not easy.

**Comment by ZdenekKrcal** [comment]
Thank you it is much better now.

**Comment by ZdenekKrcal** [comment]
one thing yet, on touch screen the Tooltip does'n show.  Where could be problem?

**Comment by entronad** [comment]
Such settings works fine in my cases, and it seems good in your web case in your video, so is your touch case realy on a `PointerDeviceKind.touch` device? try changing this setting.

**Comment by ZdenekKrcal** [comment]
> PointerDeviceKind.touch

yes, im using web app installed on mobile phone  (PWA), and Im using display of mobile phone but tooltip doesnt show. It is working on the classic web desktop with mouse.

**Comment by entronad** [comment]
I'm not sure which PointerDeviceKind works for you, you can print the gesture.device in a updater function or try different kinds to find out which one fits for you. Maybe null(which means all) is the best.

**Comment by ZdenekKrcal** [comment]
> I'm not sure which PointerDeviceKind works for you, you can print the gesture.device in a updater function or try different kinds to find out which one fits for you. Maybe null(which means all) is the best.

Yes I set null on device and it is working now, thank you. So performance is better now but on the web is still a little laggy.

**Comment by entronad** [comment]
The Flutter web is not that perfect now, especially on a mobile device, I heard it's rendered by dom and canvas now. Maybe it will be better if rendered by webassembly in the future.

**Comment by ZdenekKrcal** [comment]
> The Flutter web is not that perfect now, especially on a mobile device, I heard it's rendered by dom and canvas now. Maybe it will be better if rendered by webassembly in the future.

Yes lets hope that it will be better in the future. Thank you for your help.

**Comment by anggaaryas** [comment]
Hi @entronad , any tips for handle large data for zooming and scrolling?

**Comment by entronad** [comment]
@anggaaryas  Use less labels as this issue shows, set `rebuild` and `changeData` to false if you don't need.

**Comment by anggaaryas** [comment]
is make `Label('')` in `LineElement` and point `size = 0` in `PointElement` in `encoder` make the chart not render that label and point?

from your tips. it works when I not use label in LineElement , the performance is better. But I want to show some label using encoder (maybe just 1 or 2) .

**Comment by anggaaryas** [comment]
or maybe encoder should accept null?

**Comment by entronad** [comment]
The labels can only be all rendered or none rendered now. I will take your advice to make it nullable.(Label('') will not help because layout function has still to be executed).

Mean while if you has only 1 or 2 labels, I suggest you to use TagAnnotation instead. Or you can extend your own `Shape` class to avoid rendering all labels.

**Comment by entronad** [comment]
In v0.9.1, `Label` will also accept a null text. If the `Lable.text` is null or empty, it will not render for better performance.

**Comment by jalixdesign** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
DarthVagen, @StevenL2017, @jxpeng98, @RainmanGT, @uncleguanghui, @myywlc, @leapahea, @liulaojian, @threebowrice, @oddwatcher, @nhfmaster, @luckyuncle, @liweidong32768, @codingonion, @liyang85105, @wuyu9527, @iqgnat, @wmil, @kewangnet, @tuangeek, @861130245, @SSymbol, @JiaqiXiang-nb, @tianyikenan, @201708034122, @clientsfromhell, @gooyan, @zhaodc, @zhaozhiqiang, @dragonwong, @h4m5t, @congwang1998, @yichangle0410, @jaykon, @barry800414, @chenshipku, @nickattw, @qiubinglin, @Infi-zc, @wangyiqun1985, @ChatRichAi, @WangJinshans, @magnusguo, @xiaofeng9527, @ianmage, @CodeNeverStops, @lebin, @nerr, @2723070053, @IT-FE-Josh
