### ISSUE TITLE
Understanding gradients 'stops'

### ISSUE THREAD

**Issue by anggaaryas** [entronad/graphic#53]
from the library, it says:

```
  /// A list of values from 0.0 to 1.0 that denote fractions along the gradient.
  ///
  /// If non-null, this list must have the same length as [colors].
  ///
  /// If the first value is not 0.0, then a stop with position 0.0 and a color
  /// equal to the first color in [colors] is implied.
  ///
  /// If the last value is not 1.0, then a stop with position 1.0 and a color
  /// equal to the last color in [colors] is implied.
  ///
  /// The values in the [stops] list must be in ascending order. If a value in
  /// the [stops] list is less than an earlier value in the list, then its value
  /// is assumed to equal the previous value.
  ///
  /// If stops is null, then a set of uniformly distributed stops is implied,
  /// with the first stop at 0.0 and the last stop at 1.0.
```

so, `stops:[0,1]` (default) is just like normal gradient, right?

the problem is, when the data has fewer spike, the gradient is wrong

![Screenshot_1644552473](https://user-images.githubusercontent.com/36914072/153536422-66e052cf-a56a-43f6-bc87-1e0c5c705eab.png)
![Screenshot_1644552487](https://user-images.githubusercontent.com/36914072/153536431-e094677a-82ea-4162-b8a4-9a8235e7ee89.png)

any solution?

**Comment by anggaaryas** [comment]
I found the solution!!!

```
ShaderMask(
     shaderCallback: (rect) => LinearGradient(...)
     child: Chart(..)
)
```

use `ShaderMask` outside your `Chart` widget. Maybe can you tell me which file to render gradient? I am still understanding your library. maybe I can contribute to this library

**Comment by entronad** [comment]
If you are interested:
This file transforms a painting.Gradient to ui.Gradient. painting.Gradient is used for specification because it can define relative positioned color stops:
https://github.com/entronad/graphic/blob/main/lib/src/shape/util/gradient.dart

This file is how gradient is rendered, simply setting the Paint:
https://github.com/entronad/graphic/blob/5498c6eedd87867078b652859e0287bbfae5bfde/lib/src/shape/util/render_basic_item.dart#L29

**Comment by anggaaryas** [comment]
ok, thank you for the response. for now, I will close this issue

**Comment by entronad** [comment]
In version 0.9.1, we updated the shape gradient calculation, so that the coordinate constraint is also considered and stops will not overflow the coordinate region.

**Comment by anggaaryas** [comment]
@entronad thank you. you are so fast
