### ISSUE TITLE
set PolarCoord backround color radius

### ISSUE THREAD

**Issue by dJani97** [entronad/graphic#56]
Hi!

I'd like to re-create the rings of this [Echarts example](https://echarts.apache.org/examples/en/editor.html?c=gauge-ring) in Graphic.

<img src="https://user-images.githubusercontent.com/22769564/155638113-e292750b-c155-454a-9278-33c5b37bbfd9.png" width="300">

This is what I've got so far:

<img src="https://user-images.githubusercontent.com/22769564/155639343-38027add-f147-4138-83c1-357843f28868.png" width="300">

I figured out how to add the "border color" effect with a secondary `IntervalElement`, but I can't figure out how to limit the background color to be drawn only behind the lines. I'd like the center to remain white.

Here's my code:

    Chart(
      data: basicData,
      variables: {
        'genre': Variable(
          accessor: (Map map) => map['genre'] as String,
        ),
        'sold': Variable(
          accessor: (Map map) => map['sold'] as num,
          scale: LinearScale(min: 0),
        ),
      },
      elements: [
        IntervalElement(
          color: ColorAttr(variable: 'genre', values: [Color(0xff464646), Color(0xff464646), Color(0xff464646)]),
          shape: ShapeAttr(
            value: RectShape(borderRadius: const BorderRadius.all(Radius.circular(10))),
          ),
          size: SizeAttr(value: -16.5),
        ),
        IntervalElement(
          color: ColorAttr(variable: 'genre', values: eChartColors),
          shape: ShapeAttr(
            value: RectShape(borderRadius: const BorderRadius.all(Radius.circular(11.5))),
          ),
          size: SizeAttr(value: -15),
        ),
      ],
      coord: PolarCoord(
        transposed: true,
        startRadius: 0.7,
        endRadius: 1,
        color: Color(0xffE6EBF8),
      ),
      selections: {'tap': PointSelection()},
      tooltip: TooltipGuide(renderer: centralPieLabel),
    )
    
    const eChartColors = [
      Color(0xfffac858),
      Color(0xff91cc75),
      Color(0xff5470c6),
    ];

**Comment by entronad** [comment]
The "background ring" you needed, I suggest you to use the [MarkAnnotation](https://pub.dev/documentation/graphic/latest/graphic/MarkAnnotation-class.html) . With settings of `layer`s of the ring and elements, you can put it under elements. The [Paths.sector](https://pub.dev/documentation/graphic/latest/graphic/Paths/sector.html) with a 2pi angle can help you draw the ring easyly.

**Comment by dJani97** [comment]
Thank you!
