### ISSUE TITLE
Border radius behaves weird

### ISSUE THREAD

**Issue by dJani97** [entronad/graphic#58]
I'm using the Race Chart and Pie Chart from the example project.

<br>

Adding a circular border radius results in the borders twisting outwards:

![image](https://user-images.githubusercontent.com/22769564/156262299-bb332ae2-b657-4183-ad7e-baaa54f0480c.png)

<br>

A seemingly good workaround is to have a negative size for the IntervalElement (similar to what I had here https://github.com/entronad/graphic/issues/56):

![image](https://user-images.githubusercontent.com/22769564/156262547-b0ad4941-0cf6-44be-8c25-cd0d0623af90.png)

Although this introduces some problems.
<br>
For example, when any input is zero, the border twists backwards:

![image](https://user-images.githubusercontent.com/22769564/156262662-298bfab9-c683-45d8-aaa4-72a07286e330.png)

<br>

This can be corrected by checking the input data and replacing each `0` value to a non-zero value, for example `1`. One of the reasons I do not like this solution is because the _data_ must be manipulated.
Also, it still does not look too appealing to me. The "dots" representing empty values now have different lengths. For these two reasons it's not a good solution:

![image](https://user-images.githubusercontent.com/22769564/156262796-9a92f911-058f-43b4-ae64-67109e608f77.png)

<br>

**Another problem** that might be related: setting the border radius to overly high values results in all lines becoming "sausages":

![image](https://user-images.githubusercontent.com/22769564/156264447-8b20cdfa-4470-4a40-a0b9-da237cc416ef.png)

The above problems also apply to other types of charts

![image](https://user-images.githubusercontent.com/22769564/156265432-7eac28f5-7640-4674-ac40-52fb2af84fc6.png)

![image](https://user-images.githubusercontent.com/22769564/156265723-da2083cc-ff15-4244-bf3e-cefcca02853d.png)

## Expectation

In the case of e-charts, I see two different behaviors. When the value is set to 0, the a **gauge-chart** draws a small round dot. A **pie-charts** simply do not draw the slice.

![image](https://user-images.githubusercontent.com/22769564/156263491-63daedcd-e916-4a51-bfec-34289879935b.png)

**Comment by entronad** [comment]
I shall look into it.

**Comment by entronad** [comment]
Fixed in v0.9.3
