### ISSUE TITLE
How to select which variable is used in chart element?

### ISSUE THREAD

**Issue by anggaaryas** [entronad/graphic#60]
Hi, how can I choose which variable that will show in chart? is it use `position:` ?

btw, can you explain me what Varset should be accepted in:

```
    assert(form.variablesByDim.every((dim) {
      final scale = scales[dim.first];
      for (var variable in dim) {
        if (scales[variable] != scale) {
          return false;
        }
      }
      return true;
    }));
```
in position.dart 79

actually I want to use CandleStick Shape that use 4 point.

**Comment by entronad** [comment]
1. This can be seen in the doc of `Varset` class: https://pub.dev/documentation/graphic/latest/graphic/Varset-class.html
2. This assertion is to make sure that scales in the same dim (but defined in different variables) have same properties (like max and min).
3. A candle stick example is here: https://github.com/entronad/graphic/blob/f808963a7001f54b48b95e538501d6e67a4ab93d/example/lib/pages/polygon_custom.dart#L683
