### ISSUE TITLE
How to display the crosshair for the specified point by default when the chart first loaded?

### ISSUE THREAD

**Issue by orliu** [entronad/graphic#61]
As title..

I am so happy to discover and use this amazing chart. I use it to show squiggly lines, I need to show the crosshair for the special point by default when the chart is first loaded.  But I don't know how to do it.

**Comment by entronad** [comment]
Set `GeomElement.selected` to the point you want, and bind the crosshair the that `selection`
https://pub.dev/documentation/graphic/latest/graphic/GeomElement/selected.html

**Comment by orliu** [comment]
> 

Got it. Thank you!
