### ISSUE TITLE
Hide tooltips after a duration ?

### ISSUE THREAD

**Issue by litang0908** [entronad/graphic#64]
Hi, 
Thanks for this amazing repo, the only question is how can hide the tooltip after a duration?

**Comment by entronad** [comment]
This is a good question! I haven't thought before.

Here is my idea to achieve that:

The tooltip is controlled by [selection](https://pub.dev/documentation/graphic/latest/graphic/Selection-class.html), showing triggered by `on` signals and hiding triggered by `clear` signals (doubleTap by default). 

There is a way to emit and detect signals manually: the [signalChannel](https://pub.dev/documentation/graphic/latest/graphic/GeomElement/selectionChannel.html) of the element. it is a Dart StreamController. By this method, you can do some magic, like when tooltip is triggered by tapping, record and start a timer, and emit a doubleTap signal back to the chart after a duration.

Please try this way.

**Comment by litang0908** [comment]
Thank you for your reply, i will try it later then add more feedbacks.
