### ISSUE TITLE
Alignment of bars when using time scale

### ISSUE THREAD

**Issue by sprimm98** [entronad/graphic#67]
Hello, first of all, thanks for your amazing work!

Based on your stacked bar chart example, I am using TimeScale to show the abbreviations of the last seven days as the x axis components. This is my code for the "date" variable:

```
"date": Variable(
  accessor: (Map map) {
    return map["date"] as DateTime;
  },
  scale: TimeScale(
    min: DateTime.now().subtract(const Duration(days: 6)),
    max: DateTime.now(),
    tickCount: 7,
    formatter: (date) {
      return intl.DateFormat.E(Localizations.localeOf(context).toLanguageTag()).format(date);
    },
  ), 
)
```

This works quite nice, but the ticks aren't alignment with the bars anymore as shown in the following screenshot:

![Screenshot_20220320-144110](https://user-images.githubusercontent.com/91949891/159166047-b0c6980a-0807-4115-b256-f73e0d50202a.png)

The shown bar is the "Thursday one", but it's placed between Wednesday and Thursday. Is there any way to fix this?

**Comment by entronad** [comment]
The TimeScale is a continuous scale like LinearScale, its tick positions are calculated by the time span (from min to max) divides tickCount.

I notice that your max is DateTime.now(), So if "now" is not the beginning or middle of a day, the ticks will not be the beginning or middle.

The solution is to use a OrdinalScale (it seems you only concerns discrete days), or make sure the max and min is what you want.

**Comment by sprimm98** [comment]
You're totally right, using DateTime.now() results in wrong placing depending on the current time. I removed the min and max properties and used ticks instead to generate a list of DateTimes of the start of each days. After that the alignment was right again. Thanks.
