### ISSUE TITLE
How does shape use gradients or textures?

### ISSUE THREAD

**Issue by unrealsmart** [entronad/graphic#7]
https://g.antv.vision/en/docs/api/shape/attrs#%E7%BA%B9%E7%90%86

**Comment by entronad** [comment]
Custom your own Shape class and set your own shader of the renderShapes in it, like:
https://github.com/entronad/graphic/blob/43d020e33fd536074f732ba53afcb4da9e0a15f1/example/lib/pages/custom_shape_page.dart#L9

**Comment by unrealsmart** [comment]
yes, like this
![image](https://user-images.githubusercontent.com/11688458/103370679-5bfc1200-4b08-11eb-98f4-d3e4e3590b48.png)
I can't find the shape to set the picture, maybe there are a lot of icons

**Comment by entronad** [comment]
No picture marker yet.
