### ISSUE TITLE
请问如何在一个chart中引入多个数据源 实现在一张图上做多个曲线?

### ISSUE THREAD

**Issue by jiangweihu** [entronad/graphic#71]

**Comment by implion** [comment]
你可以看看他的example里面的echats的案例，里面有怎么实现多个曲线的方法

**Comment by jiangweihu** [comment]
> 

你好, 我看了例子, 我的理解 echarts中是一个数据源data 通过position对data进行了处理, 我的问题是想多个数据源data(至少有20个数据源 也就是20条曲线)
