### ISSUE TITLE
sunburst charts

### ISSUE THREAD

**Issue by shitb** [entronad/graphic#72]
I ran the sample, but I can't find the sunburst chart code, does this library support it? thanks

**Comment by entronad** [comment]
If the sunburst chart you mean involves tree shaped data structure, the answer is no.

**Comment by shitb** [comment]
> If the sunburst chart you mean involves tree shaped data structure, the answer is no.

Thank you for your reply. Please ask if there are any plans to support sunburst.

**Comment by entronad** [comment]
There is a plan to support nested data structure charts (sanky, treemap, sunburst). But it will take a long time

**Comment by shitb** [comment]
> There is a plan to support nested data structure charts (sanky, treemap, sunburst). But it will take a long time

Great work!
