### ISSUE TITLE
touch hover event

### ISSUE THREAD

**Issue by mohamed-adly** [entronad/graphic#73]
Is there is an event that give the current touched element in the series?
i would like to make  some calculation based on the touch move and show the result in different widget

**Comment by entronad** [comment]
See the Selection Channel example:
https://github.com/entronad/graphic/blob/72b9b32ffe1da3532c6743ef7a0ab03f4df0d351/example/lib/pages/interaction_channel_dynamic.dart#L185

**Comment by mohamed-adly** [comment]
Thank you 
that helped a lot.
