### ISSUE TITLE
The chart cannot be refreshed after changing the list data,

### ISSUE THREAD

**Issue by cailingyun2010** [entronad/graphic#8]
use radius rect

change map['genre'] value or map['sold']

The interface overlaps and cannot be refreshed

**Comment by morio77** [comment]
same (Android）

**Comment by cailingyun2010** [comment]
In fact, the document explains how to refresh the chart, which is about the life cycle.

If you are new to flutter, you can solve it like this:
Create two widgets, mark them with a bool, and switch back and forth to display widget A and widget B, so that data refresh can be achieved

**Comment by morio77** [comment]
Thank you very much.

I was able to update the screen.
