### ISSUE TITLE
Support for 2D error band

### ISSUE THREAD

**Issue by heri16** [entronad/graphic#81]
Do we have full support for 2D error band like in vega-lite?

https://vega.github.io/vega-lite/docs/errorband.html#pre-aggregated-usage

![6C1AF303-C9A9-4E4A-932D-4C0CFB3963FC](https://user-images.githubusercontent.com/527101/162569100-6b66e2b3-ddc7-43a8-9c44-9e6c797a1a4c.jpeg)

**Comment by heri16** [comment]
Also called a "Range Area Chart"?

https://g2.antv.vision/en/examples/area/range#range

**Comment by entronad** [comment]
If you set the position of an AreaElement like `Varset('time') * (Varset('min') + Varset('max'))`, it is an range area from min to max.

In fact , an AreaElement is always a range area, if you set only one varset for y, the range starts from 0.
