### ISSUE TITLE
Axis guides rendering outside of the given constraints

### ISSUE THREAD

**Issue by canastro** [entronad/graphic#87]
### Overview
The charts AxisGuide are rendering the labels outside of the given size of the chart. In the following example one would expect that nothing would be rendered outside of the red area.

### Given
```dart
Container(
  color: Colors.red.withOpacity(0.5),
  margin: const EdgeInsets.only(top: 10),
  width: 350,
  height: 300,
  child: Chart(
    data: basicData,
    variables: {
      'genre': Variable(
        accessor: (Map map) => map['genre'] as String,
      ),
      'sold': Variable(
        accessor: (Map map) => map['sold'] as num,
      ),
    },
    elements: [IntervalElement()],
    coord: RectCoord(transposed: true),
    axes: [
      AxisGuide<void>(
        label: LabelStyle(
          style: const TextStyle(color: Colors.black),
          offset: const Offset(-7.5, 0),
          minWidth: 0,
          maxWidth: 100,
        ),
      ),
      Defaults.horizontalAxis,
    ],
  ),
),
```

### Then

![Screenshot 2022-04-18 at 14 56 58](https://user-images.githubusercontent.com/1267623/163818710-72aa777e-63a7-4e7c-bbdc-29cbe43fe862.png)

### Expected
The chart's content should be pushed by a value between 0 and 100px. In this case, since the label overflows it should be pushed by 100px. 

### Other
I've been trying to figure out how this could be done in graphic and its really tricky, couldnt figure out any clean way to do this.

**Comment by canastro** [comment]
Right now, since I couldn't figure out a good way to do this within Graphic, I'm addressing this on the user-land.
I'm computing my approximately max label's width and updating the chart's padding. 

Still, it could be nice to figure out a good way to address this as many users might render a chart aligned to the left of a page and see their labels overflowing and getting hidden.

**Comment by entronad** [comment]
I think what you mean is "auto-margin": the default margin(width between chart widget border and coordinate border) is not a static value, it is automatically calculated by the max length of axis labels.

Some other charting libs have such feature, and we have considered it in the beginning. But finally we decided not to have such functions. The margins of the chart are values. If the label width varies a lot, users should do the calculation(as you did in the reply).

The reasons is: 

When people say "I just need a simple auto-adjusted margin", they have various requests in mind: how much is the additional distance between the label and border, how to handle if only one label is too long, what to do if the result coord region is too small? The best margin calculation is complex in fact.

So, if the user really don't care much about the margin, or they know the max width of labels , setting the max value or an approximate value is the simplest and best way. One the other hand, if there are additional requests, Let the user do the calculation is the best, they know the labels and chart designs best.

**Comment by canastro** [comment]
Alright, I think it's ok to close this issue then. If someone else requests such a feature again in the future you can guide them to this comment.
