### ISSUE TITLE
Support Animations

### ISSUE THREAD

**Issue by josh-burton** [entronad/graphic#90]
Does this library support animating chart data? Specifically I'm looking to animate a line chart with the line animating from left to right.

**Comment by entronad** [comment]
Not yet. There is a plan about animation, but that will take a long time.

**Comment by entronad** [comment]
Can you give an example of the animation you want?

**Comment by josh-burton** [comment]
I think there are 2 types of animations:

- entrance animation - the initial display of the graph
- animating between data sets

My use case is primarily for line graphs.

Example of a common entrance animation: https://cdn.dribbble.com/users/3593/screenshots/2475280/linechart.gif
This is basically the line graph animation from left to right. I'd also want to be able to animate any 'area' under the line.

Example of animating between data sets: https://www.youtube.com/watch?v=xYLLaqKG53I

**Comment by entronad** [comment]
Thanks

**Comment by maxim-drobonoh** [comment]
@entronad Hi, any news about animation support ?

**Comment by entronad** [comment]
@maxim-drobonoh I am working on it now, upgrade the engine for animation, you can see that from recent commits on main branch.

**Comment by maxim-drobonoh** [comment]
@entronad Great! I've found this library so useful and flexible, thanks for that! And I'm impatient to see next release with animation support. Do you have any expectations when it could be done.?

**Comment by entronad** [comment]
@maxim-drobonoh At least needs another two months.
