### ISSUE TITLE
TagAnnotation does not clip to inside the AxisGuide while LineAnnotation does 

### ISSUE THREAD

**Issue by jamesblasco** [entronad/graphic#93]
https://user-images.githubusercontent.com/19904063/164676133-fe0d30b2-176c-488c-a302-7ccc1e2f8404.mov

I have a graph where I add a vertical line at the start of each month. The line annotation does not render outside the graph bounds while the label does. Could they have the same behaviour? Or be able to control it

```dart 
[
            LineAnnotation(
              dim: Dim.x,
              value: DateTime.now(),
              variable: 'date',
              style: StrokeStyle(
                color: Colors.grey,
              ),
            ),
            TagAnnotation(
              label: Label(
                DateFormat('MMM').format(value: DateTime.now()),
                LabelStyle(
                  offset: Offset(7.5, 0),
                  align: Alignment.centerRight,
                  style: TextStyle(color: Colors.grey, fontSize: 14),
                ),
              ),
              values: [item.date, monthLabelYPosition],
              variables: ['date', 'value'],
            ),
]
```

**Comment by entronad** [comment]
Usually, for annotations, lines and areas need clip while label and figures doesn't.

But I haven't considered your situation.

I shall add a clip switch for labels and figures.

**Comment by entronad** [comment]
Added in v0.10.1
