### ISSUE TITLE
Can i separate area color using encoder?

### ISSUE THREAD

**Issue by anggaaryas** [entronad/graphic#98]
![InvertChart15](https://user-images.githubusercontent.com/36914072/167536321-374de0af-664e-4ea4-97be-48bb888872e1.png)

for example:
```
encoder : (variable){ 
    if( variable['value'] < 0) return Colors.red;
    else return Colors.green;
}
```

but, for now. it can not separate color, any solution? or maybe i should make 2 areaElement, red area chart and green area chart?

**Comment by anggaaryas** [comment]
some alternative solution: use `IntervalElement` rather than `AreaElement`

**Comment by entronad** [comment]
The best way I suggest is to custom your own AreaShape subclass and override the rendering methods.

**Comment by anggaaryas** [comment]
ok, i will try it 👍

**Comment by anggaaryas** [comment]
btw should i add this custom shape to library?

**Comment by entronad** [comment]
If you think your shape may be widely used, you can please make a PR and let's discuss then.

**Comment by anggaaryas** [comment]
ok, i will not add to library. because i just using rect coord.
